// AUTO-GENERATED by scripts/bundle_odoo_search_function.js — no editar a mano
// <<SEMANTIC_CATALOG_START>>
const SEMANTIC_CATALOG = {
  "schema_version": "life_catalog_semantic_v1",
  "synced_at": "2026-07-19T18:00:00Z",
  "sports_allowed": [
    "futbol",
    "baloncesto",
    "voleibol",
    "atletismo"
  ],
  "sports_declined_examples": [
    "natación",
    "ciclismo",
    "béisbol",
    "hockey",
    "patinaje",
    "motocross",
    "motociclismo",
    "porras",
    "equitación",
    "tenis",
    "pádel",
    "rugby",
    "waterpolo",
    "balonmano"
  ],
  "commercial_policies": {
    "no_volume_discount": true,
    "fabricantes_precios_minimos": true,
    "default_material": "dry_fit",
    "no_fabric_upsell": true,
    "field_uniform_bottom": "pantaloneta",
    "rompevientos_odoo_id": 68,
    "peto_odoo_id": 69,
    "catalog_url": "https://lifedeportes.odoo.com/shop",
    "address_es": "Cl. 66a #98a 12, barrio Los Álamos, Engativá, Bogotá"
  },
  "garment_types": {
    "uniforme_completo": "Camiseta + pantaloneta (+ medias en fútbol base)",
    "camiseta_sola": "Solo camiseta; producto base vendible desde 6 u. del mismo producto/diseño",
    "pantaloneta": "Short / pantaloneta suelta",
    "medias": "Medias",
    "arquero": "Prendas o conjunto arquero",
    "sudadera_conjunto": "Sudaderas, buzos, hoodies (no rompevientos)",
    "chaqueta": "Chaqueta Rompevientos (68) o Chaqueta Lotto (1800)",
    "peto": "Peto sublimado (69)"
  },
  "variant_dimensions": {
    "collar": [
      "cuello_v",
      "cuello_redondo",
      "polo_sin_botones",
      "polo_con_botones",
      "cuello_sport"
    ],
    "sleeves": [
      "manga_corta",
      "manga_larga",
      "manga_sisa",
      "ranglan"
    ],
    "material": [
      "dry_fit",
      "dumonti",
      "hidrotec",
      "lluvia"
    ],
    "short_style": [
      "standard",
      "lycra",
      "impermeable",
      "mariposa",
      "bolsillos"
    ]
  },
  "commercial_rules": {
    "uniform_base_min_qty": 6,
    "base_role": "base_uniform",
    "extra_roles": [
      "extra"
    ],
    "design_role": "design",
    "standalone_product_min_qty": 6,
    "standalone_base_role": "base_product"
  },
  "families": {
    "otros_general": {
      "family_key": "otros_general",
      "price_from_cop": 5000,
      "base_odoo_id": 1802,
      "base_name": "Extra chaqueta con cremallera en cada lado",
      "member_count": 21,
      "members": [
        {
          "odoo_id": 1802,
          "name": "Extra chaqueta con cremallera en cada lado",
          "list_price_cop": 5000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1803,
          "name": "Extra pantalon con cremallera en cada lado",
          "list_price_cop": 5000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1805,
          "name": "Incrementos de precio: a partir de la 2xl:",
          "list_price_cop": 5000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1794,
          "name": "Bordado adicional",
          "list_price_cop": 7000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1806,
          "name": "Incrementos de precio: a partir de la 3xl",
          "list_price_cop": 10000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1804,
          "name": "Gorras con un bordado",
          "list_price_cop": 15000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 70,
          "name": "Tulas",
          "list_price_cop": 18000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 177,
          "name": "Petos en malla",
          "list_price_cop": 25000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 69,
          "name": "Petos sublimados",
          "list_price_cop": 28000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1188,
          "name": "Lycra",
          "list_price_cop": 30000,
          "material": "dry_fit",
          "variant": "lycra"
        },
        {
          "odoo_id": 179,
          "name": "Buzo de arquero",
          "list_price_cop": 31000,
          "material": "dry_fit",
          "variant": "arquero"
        },
        {
          "odoo_id": 159,
          "name": "Diseño especial (arquero o jugador) si son menos de 6 unidades",
          "list_price_cop": 35000,
          "material": "dry_fit",
          "variant": "arquero"
        },
        {
          "odoo_id": 163,
          "name": "Pantalón de arquero",
          "list_price_cop": 45000,
          "material": "dry_fit",
          "variant": "arquero"
        },
        {
          "odoo_id": 67,
          "name": "Pantalón de sudadera",
          "list_price_cop": 45000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 194,
          "name": "Banderas, 1.10 X 1.50",
          "list_price_cop": 60000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1800,
          "name": "Chaqueta Lotto",
          "list_price_cop": 60000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 68,
          "name": "Chaqueta Rompevientos",
          "list_price_cop": 60000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1795,
          "name": "Busos con capota",
          "list_price_cop": 65000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 178,
          "name": "Conjunto de arquero",
          "list_price_cop": 70000,
          "material": "dry_fit",
          "variant": "arquero"
        },
        {
          "odoo_id": 66,
          "name": "Sudadera Chaqueta y Pantalón Orión",
          "list_price_cop": 100000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1811,
          "name": "Sudaderas en algodón lycrado con bordados",
          "list_price_cop": 120000,
          "material": "dry_fit",
          "variant": "lycra"
        }
      ]
    },
    "camiseta_manga_corta": {
      "family_key": "camiseta_manga_corta",
      "price_from_cop": 30000,
      "base_odoo_id": 62,
      "base_name": "Camiseta deportiva dry-fit",
      "member_count": 3,
      "members": [
        {
          "odoo_id": 62,
          "name": "Camiseta deportiva dry-fit",
          "list_price_cop": 30000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1797,
          "name": "Camiseta deportiva lluvia",
          "list_price_cop": 33000,
          "material": "lluvia",
          "variant": "lluvia"
        },
        {
          "odoo_id": 685,
          "name": "Camiseta Deportiva Dumonti",
          "list_price_cop": 35000,
          "material": "dumonti",
          "variant": "dumonti"
        }
      ]
    },
    "camiseta_polo": {
      "family_key": "camiseta_polo",
      "price_from_cop": 33000,
      "base_odoo_id": 61,
      "base_name": "Camiseta deportiva con cuello polo, Sin botones",
      "member_count": 1,
      "members": [
        {
          "odoo_id": 61,
          "name": "Camiseta deportiva con cuello polo, Sin botones",
          "list_price_cop": 35000,
          "material": "dry_fit",
          "variant": "polo_sin_botones"
        }
      ]
    },
    "medias": {
      "family_key": "medias",
      "price_from_cop": 7500,
      "base_odoo_id": 113,
      "base_name": "Medias semi",
      "member_count": 2,
      "members": [
        {
          "odoo_id": 113,
          "name": "Medias semi",
          "list_price_cop": 7500,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1807,
          "name": "Medias profesionales",
          "list_price_cop": 10000,
          "material": "dry_fit",
          "variant": "base"
        }
      ]
    },
    "pantaloneta": {
      "family_key": "pantaloneta",
      "price_from_cop": 25000,
      "base_odoo_id": 1808,
      "base_name": "Pantalonetas",
      "member_count": 2,
      "members": [
        {
          "odoo_id": 1808,
          "name": "Pantalonetas",
          "list_price_cop": 25000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1809,
          "name": "Pantalonetas impermeables",
          "list_price_cop": 30000,
          "material": "dry_fit",
          "variant": "impermeable"
        }
      ]
    },
    "uniforme_manga_corta": {
      "family_key": "uniforme_manga_corta",
      "price_from_cop": 50000,
      "base_odoo_id": 115,
      "base_name": "Uniforme de Fútbol",
      "member_count": 6,
      "members": [
        {
          "odoo_id": 115,
          "name": "Uniforme de Fútbol",
          "list_price_cop": 50000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 35,
          "name": "Uniforme de atletismo",
          "list_price_cop": 50000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 23,
          "name": "Uniforme de baloncesto",
          "list_price_cop": 50000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 31,
          "name": "Uniforme de voleibol",
          "list_price_cop": 50000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1819,
          "name": "Uniformes con bordado",
          "list_price_cop": 57000,
          "material": "dry_fit",
          "variant": "base"
        },
        {
          "odoo_id": 1813,
          "name": "Uniformes camiseta doble faz y pantaloneta",
          "list_price_cop": 85000,
          "material": "dry_fit",
          "variant": "base"
        }
      ]
    },
    "uniforme_polo": {
      "family_key": "uniforme_polo",
      "price_from_cop": 58000,
      "base_odoo_id": 8,
      "base_name": "Uniforme de Presentación (Futbol polo)",
      "member_count": 1,
      "members": [
        {
          "odoo_id": 8,
          "name": "Uniforme de Presentación (Futbol polo)",
          "list_price_cop": 75000,
          "material": "dry_fit",
          "variant": "polo"
        }
      ]
    },
    "uniforme_dumonti": {
      "family_key": "uniforme_dumonti",
      "price_from_cop": 65000,
      "base_odoo_id": 1818,
      "base_name": "Uniformes Deportivo Dumonti",
      "member_count": 1,
      "members": [
        {
          "odoo_id": 1818,
          "name": "Uniformes Deportivo Dumonti",
          "list_price_cop": 65000,
          "material": "dumonti",
          "variant": "dumonti"
        }
      ]
    }
  },
  "products": [
    {
      "odoo_id": 194,
      "name": "Banderas, 1.10 X 1.50",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 60000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Bandera institucional 1.10 × 1.50 m personalizada.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1794,
      "name": "Bordado adicional",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 7000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1795,
      "name": "Busos con capota",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 65000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Buso con capota en algodón Lotto sublimable.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 179,
      "name": "Buzo de arquero",
      "category": "otros",
      "variant": "arquero",
      "material": "dry_fit",
      "list_price_cop": 31000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 685,
      "name": "Camiseta Deportiva Dumonti",
      "category": "camiseta",
      "variant": "dumonti",
      "material": "dumonti",
      "list_price_cop": 35000,
      "family_key": "camiseta_manga_corta",
      "is_published": true,
      "description_sale": "Camiseta deportiva Dumonti personalizada.",
      "commercial_role": "base_product",
      "min_qty_standalone": 6,
      "allow_without_base": true,
      "is_base": false
    },
    {
      "odoo_id": 61,
      "name": "Camiseta deportiva con cuello polo, Sin botones",
      "category": "camiseta",
      "variant": "polo_sin_botones",
      "material": "dry_fit",
      "list_price_cop": 35000,
      "family_key": "camiseta_polo",
      "is_published": true,
      "description_sale": "Camiseta deportiva cuello polo personalizada.",
      "commercial_role": "base_product",
      "min_qty_standalone": 6,
      "allow_without_base": true,
      "is_base": true
    },
    {
      "odoo_id": 62,
      "name": "Camiseta deportiva dry-fit",
      "category": "camiseta",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 30000,
      "family_key": "camiseta_manga_corta",
      "is_published": true,
      "description_sale": "Camiseta deportiva dry-fit personalizada.",
      "commercial_role": "base_product",
      "min_qty_standalone": 6,
      "allow_without_base": true,
      "is_base": true
    },
    {
      "odoo_id": 1797,
      "name": "Camiseta deportiva lluvia",
      "category": "camiseta",
      "variant": "lluvia",
      "material": "lluvia",
      "list_price_cop": 33000,
      "family_key": "camiseta_manga_corta",
      "is_published": true,
      "description_sale": "Camiseta deportiva para lluvia personalizada.",
      "commercial_role": "base_product",
      "min_qty_standalone": 6,
      "allow_without_base": true,
      "is_base": false
    },
    {
      "odoo_id": 1800,
      "name": "Chaqueta Lotto",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 60000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Chaqueta en algodón Lotto sublimable.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 68,
      "name": "Chaqueta Rompevientos",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 60000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Chaqueta rompevientos con capota personalizada.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 178,
      "name": "Conjunto de arquero",
      "category": "otros",
      "variant": "arquero",
      "material": "dry_fit",
      "list_price_cop": 70000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Conjunto de arquero personalizado.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 159,
      "name": "Diseño especial (arquero o jugador) si son menos de 6 unidades",
      "category": "otros",
      "variant": "arquero",
      "material": "dry_fit",
      "list_price_cop": 35000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "design",
      "min_qty_standalone": 1,
      "allow_without_base": true,
      "is_base": false
    },
    {
      "odoo_id": 1802,
      "name": "Extra chaqueta con cremallera en cada lado",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 5000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1803,
      "name": "Extra pantalon con cremallera en cada lado",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 5000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1804,
      "name": "Gorras con un bordado",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 15000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Gorra con un bordado incluido.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1805,
      "name": "Incrementos de precio: a partir de la 2xl:",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 5000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1806,
      "name": "Incrementos de precio: a partir de la 3xl",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 10000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1188,
      "name": "Lycra",
      "category": "otros",
      "variant": "lycra",
      "material": "dry_fit",
      "list_price_cop": 30000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1807,
      "name": "Medias profesionales",
      "category": "medias",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 10000,
      "family_key": "medias",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 113,
      "name": "Medias semi",
      "category": "medias",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 7500,
      "family_key": "medias",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1808,
      "name": "Pantalonetas",
      "category": "pantaloneta",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 25000,
      "family_key": "pantaloneta",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1809,
      "name": "Pantalonetas impermeables",
      "category": "pantaloneta",
      "variant": "impermeable",
      "material": "dry_fit",
      "list_price_cop": 30000,
      "family_key": "pantaloneta",
      "is_published": false,
      "description_sale": "Con bolsillos",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 163,
      "name": "Pantalón de arquero",
      "category": "otros",
      "variant": "arquero",
      "material": "dry_fit",
      "list_price_cop": 45000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 67,
      "name": "Pantalón de sudadera",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 45000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Pantalón de sudadera personalizado.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 177,
      "name": "Petos en malla",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 25000,
      "family_key": "otros_general",
      "is_published": false,
      "description_sale": "Mas de 30 u",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 69,
      "name": "Petos sublimados",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 28000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Petos sublimados para entrenamiento.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 66,
      "name": "Sudadera Chaqueta y Pantalón Orión",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 100000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Sudadera chaqueta y pantalón tela Orión personalizados.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1811,
      "name": "Sudaderas en algodón lycrado con bordados",
      "category": "otros",
      "variant": "lycra",
      "material": "dry_fit",
      "list_price_cop": 120000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Sudadera algodón lycrado con bordados personalizados.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 70,
      "name": "Tulas",
      "category": "otros",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 18000,
      "family_key": "otros_general",
      "is_published": true,
      "description_sale": "Tula deportiva sublimada personalizada.",
      "commercial_role": "extra",
      "min_qty_standalone": 1,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 115,
      "name": "Uniforme de Fútbol",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 50000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme de fútbol personalizado (camiseta, pantaloneta y medias).",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 8,
      "name": "Uniforme de Presentación (Futbol polo)",
      "category": "uniforme",
      "variant": "polo",
      "material": "dry_fit",
      "list_price_cop": 75000,
      "family_key": "uniforme_polo",
      "is_published": true,
      "description_sale": "Uniforme de presentación polo personalizado.",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 35,
      "name": "Uniforme de atletismo",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 50000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme de atletismo personalizado (camiseta sisa y pantaloneta o licra).",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 23,
      "name": "Uniforme de baloncesto",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 50000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme de baloncesto personalizado (camiseta sisa y pantaloneta).",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 31,
      "name": "Uniforme de voleibol",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 50000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme de voleibol personalizado (camiseta y pantaloneta o licra).",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1818,
      "name": "Uniformes Deportivo Dumonti",
      "category": "uniforme",
      "variant": "dumonti",
      "material": "dumonti",
      "list_price_cop": 65000,
      "family_key": "uniforme_dumonti",
      "is_published": false,
      "description_sale": null,
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": true
    },
    {
      "odoo_id": 1813,
      "name": "Uniformes camiseta doble faz y pantaloneta",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 85000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme camiseta doble faz y pantaloneta personalizado.",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": false
    },
    {
      "odoo_id": 1819,
      "name": "Uniformes con bordado",
      "category": "uniforme",
      "variant": "base",
      "material": "dry_fit",
      "list_price_cop": 57000,
      "family_key": "uniforme_manga_corta",
      "is_published": true,
      "description_sale": "Uniforme con bordado incluido (camiseta y pantaloneta).",
      "commercial_role": "base_uniform",
      "min_qty_standalone": 6,
      "allow_without_base": false,
      "is_base": false
    }
  ],
  "product_semantics": {
    "8": {
      "garment_type": "uniforme_completo",
      "aliases": [
        "uniforme presentacion",
        "uniforme de presentacion"
      ],
      "operator_label": "Uniforme de presentación"
    },
    "23": {
      "garment_type": "uniforme_completo",
      "sports": [
        "baloncesto"
      ],
      "aliases": [
        "uniforme baloncesto",
        "uniforme basketball",
        "short mariposa"
      ],
      "short_style": "mariposa",
      "operator_label": "Uniforme baloncesto"
    },
    "31": {
      "garment_type": "uniforme_completo",
      "sports": [
        "voleibol"
      ],
      "aliases": [
        "uniforme voleibol",
        "short lycra voleibol"
      ],
      "short_style": "lycra",
      "operator_label": "Uniforme voleibol"
    },
    "35": {
      "garment_type": "uniforme_completo",
      "sports": [
        "atletismo"
      ],
      "sleeves": "manga_sisa",
      "aliases": [
        "uniforme atletismo",
        "manga sisa",
        "atletismo"
      ],
      "operator_label": "Uniforme atletismo (manga sisa)"
    },
    "61": {
      "garment_type": "camiseta_sola",
      "aliases": [
        "camiseta polo",
        "polo sin botones",
        "cuello polo camiseta",
        "camiseta tipo polo"
      ],
      "collar": "polo_sin_botones",
      "operator_label": "Camiseta cuello polo sin botones"
    },
    "62": {
      "garment_type": "camiseta_sola",
      "sports": [
        "futbol",
        "baloncesto",
        "voleibol"
      ],
      "aliases": [
        "camiseta",
        "camisa",
        "camisetas",
        "camiseta de futbol",
        "camiseta futbol",
        "camiseta normal",
        "camiseta dry fit",
        "camiseta manga corta",
        "camiseta deportiva"
      ],
      "operator_label": "Camiseta dry-fit manga corta (sola)"
    },
    "66": {
      "garment_type": "sudadera_conjunto",
      "aliases": [
        "sudadera orion",
        "sudadera completa",
        "chaqueta y pantalon",
        "conjunto sudadera"
      ],
      "operator_label": "Sudadera Chaqueta y Pantalón Orión"
    },
    "68": {
      "garment_type": "chaqueta",
      "aliases": [
        "rompevientos",
        "rompeviento",
        "chaqueta rompevientos",
        "chaqueta rompeviento",
        "impermeable",
        "chompa lluvia",
        "chaqueta impermeable"
      ],
      "operator_label": "Chaqueta Rompevientos (= rompevientos). No confundir con Chaqueta Lotto"
    },
    "69": {
      "garment_type": "peto",
      "aliases": [
        "peto",
        "petos",
        "pechera",
        "peto sublimado",
        "petos sublimados"
      ],
      "operator_label": "Peto sublimado Life"
    },
    "113": {
      "garment_type": "medias",
      "aliases": [
        "medias semi",
        "medias semiprofesionales"
      ],
      "operator_label": "Medias semi"
    },
    "115": {
      "garment_type": "uniforme_completo",
      "sports": [
        "futbol"
      ],
      "aliases": [
        "uniforme de futbol",
        "uniforme futbol",
        "kit futbol",
        "uniforme completo futbol",
        "uniforme microfutbol",
        "uniforme manga corta",
        "uniformes manga corta dry fit",
        "uniforme generico",
        "uniforme impermeable",
        "pantaloneta impermeable uniforme",
        "microfutbol uniforme",
        "uniforme bolsillos",
        "pantaloneta con bolsillos"
      ],
      "operator_label": "Uniforme completo fútbol (camiseta + pantaloneta + medias semi). Variantes Odoo: manga larga +3k, cuello sport +3k, pant. impermeable +8k, pant. bolsillos +5k, Dumonti +15k, medias pro +7k"
    },
    "178": {
      "garment_type": "arquero",
      "aliases": [
        "conjunto arquero",
        "uniforme arquero",
        "portero"
      ],
      "operator_label": "Conjunto arquero"
    },
    "685": {
      "garment_type": "camiseta_sola",
      "material": "dumonti",
      "aliases": [
        "camiseta dumonti",
        "camiseta falcao",
        "camiseta premium"
      ],
      "operator_label": "Camiseta Dumonti / Falcao"
    },
    "1188": {
      "garment_type": "pantaloneta",
      "aliases": [
        "pantaloneta lycra",
        "short lycra"
      ],
      "operator_label": "Pantaloneta lycra"
    },
    "1795": {
      "garment_type": "sudadera_conjunto",
      "aliases": [
        "buso con capota",
        "buzo con capota",
        "buso capota",
        "hoodie con capota"
      ],
      "operator_label": "Buso con capota (Lotto)"
    },
    "1797": {
      "garment_type": "camiseta_sola",
      "material": "lluvia",
      "aliases": [
        "camiseta lluvia",
        "camiseta de lluvia",
        "camiseta impermeable"
      ],
      "operator_label": "Camiseta deportiva lluvia"
    },
    "1800": {
      "garment_type": "chaqueta",
      "aliases": [
        "chaqueta lotto",
        "algodon lotto",
        "chaqueta algodon"
      ],
      "operator_label": "Chaqueta Lotto (distinta de rompevientos)"
    },
    "1807": {
      "garment_type": "medias",
      "aliases": [
        "medias pro",
        "medias profesionales"
      ],
      "operator_label": "Medias profesionales"
    },
    "1808": {
      "garment_type": "pantaloneta",
      "aliases": [
        "pantaloneta",
        "short",
        "pantaloneta standard"
      ],
      "operator_label": "Pantaloneta estándar"
    },
    "1809": {
      "garment_type": "pantaloneta",
      "aliases": [
        "pantaloneta impermeable",
        "short impermeable"
      ],
      "operator_label": "Pantaloneta impermeable"
    },
    "1811": {
      "garment_type": "sudadera_conjunto",
      "aliases": [
        "hoodie",
        "hoodies",
        "sudadera algodon",
        "sudadera con bordado",
        "sudadera lycrada"
      ],
      "operator_label": "Sudadera algodón lycrado con bordados"
    },
    "1818": {
      "garment_type": "uniforme_completo",
      "material": "dumonti",
      "aliases": [
        "uniforme dumonti",
        "uniforme falcao",
        "uniforme premium",
        "uniforme tela dumonti"
      ],
      "operator_label": "Uniforme Deportivo Dumonti"
    },
    "1819": {
      "garment_type": "uniforme_completo",
      "aliases": [
        "uniforme con bordado",
        "bordado incluido"
      ],
      "operator_label": "Uniforme con bordado incluido"
    }
  },
  "intent_defaults": [
    {
      "when_sport": "futbol",
      "when_garment": "uniforme_completo",
      "odoo_id": 115,
      "reason_es": "Uniforme fútbol dry-fit por defecto"
    },
    {
      "when_sport": "futbol",
      "when_garment": "camiseta_sola",
      "odoo_id": 62,
      "reason_es": "Camiseta dry-fit manga corta (sola) para fútbol"
    },
    {
      "when_sport": "baloncesto",
      "when_garment": "uniforme_completo",
      "odoo_id": 23,
      "reason_es": "Uniforme baloncesto por defecto"
    },
    {
      "when_sport": "voleibol",
      "when_garment": "uniforme_completo",
      "odoo_id": 31,
      "reason_es": "Uniforme voleibol por defecto"
    },
    {
      "when_sport": "atletismo",
      "when_garment": "uniforme_completo",
      "odoo_id": 35,
      "reason_es": "Uniforme atletismo manga sisa"
    },
    {
      "when_garment": "camiseta_sola",
      "when_text_includes": [
        "polo"
      ],
      "odoo_id": 61,
      "reason_es": "Camiseta polo sin botones por mención de polo"
    },
    {
      "when_garment": "uniforme_completo",
      "when_text_includes": [
        "polo"
      ],
      "odoo_id": 8,
      "reason_es": "Uniforme de Presentación (Futbol polo) — único uniforme cuello polo publicado"
    },
    {
      "when_garment": "uniforme_completo",
      "when_text_includes": [
        "dumonti",
        "falcao"
      ],
      "odoo_id": 1818,
      "reason_es": "Uniforme Deportivo Dumonti (tela premium)"
    },
    {
      "when_garment": "chaqueta",
      "when_text_includes": [
        "rompeviento"
      ],
      "odoo_id": 68,
      "reason_es": "Rompevientos = Chaqueta Rompevientos (68), no Lotto"
    },
    {
      "when_garment": "chaqueta",
      "when_text_includes": [
        "lotto"
      ],
      "odoo_id": 1800,
      "reason_es": "Chaqueta Lotto explícita"
    },
    {
      "when_garment": "chaqueta",
      "odoo_id": 68,
      "reason_es": "Chaqueta genérica → Rompevientos (68) por defecto; Lotto solo si lo nombran"
    },
    {
      "when_garment": "peto",
      "odoo_id": 69,
      "reason_es": "Peto sublimado publicado"
    }
  ],
  "colloquial_examples": [
    {
      "phrase": "camiseta de futbol",
      "likely": "Camiseta dry-fit sola (62) — no preguntar por uniforme"
    },
    {
      "phrase": "camiseta normal + foto polo",
      "likely": "Camiseta polo sin botones (61) o uniforme polo (947)"
    },
    {
      "phrase": "10 uniformes voleibol",
      "likely": "Uniforme de voleibol (31)"
    },
    {
      "phrase": "rompevientos",
      "likely": "Chaqueta Rompevientos (68) — no Lotto"
    },
    {
      "phrase": "petos",
      "likely": "Peto sublimado (69)"
    },
    {
      "phrase": "natación",
      "likely": "Deporte no ofrecido — rechazar"
    }
  ]
};
// <<SEMANTIC_CATALOG_END>>

// <<MATCH_ENGINE_START>>
/**
 * Políticas comerciales fijas Life (vendedor).
 * Fuente alineada con prompt FAQ + KB life_reglas_comerciales.
 * Usado por product_match_engine y quote_intent_parser (y bundles Kapso).
 */

const SPORTS_ALLOWED_ES = "fútbol, baloncesto, voleibol y atletismo";

/** Términos normalizados (sin tildes) de deportes que NO fabricamos. */
const SPORT_DECLINED_TERMS = [
  "natacion",
  "swimming",
  "ciclismo",
  "cycling",
  "beisbol",
  "baseball",
  "hockey",
  "patinaje",
  "motocross",
  "motociclismo",
  "equitacion",
  "porras",
  "cheer",
  "rugby",
  "tenis",
  "padel",
  "paddle",
  "waterpolo",
  "handball",
  "balonmano",
];

const FIXED_REPLIES = {
  descuento:
    "Somos fabricantes: el precio ya es el mínimo de catálogo; no manejamos rebaja adicional por cantidad.",
  direccion:
    "Estamos en la Cl. 66a #98a 12, barrio Los Álamos, Engativá, Bogotá. Puede ver el mapa aquí: https://maps.google.com/?cid=12304529363039725410",
  catalogo: "Puede ver el catálogo en https://lifedeportes.odoo.com/shop",
  pago:
    "Abono del 50% para iniciar y el 50% restante para hacer el envío (o al pasar a recogerlo en fábrica). La cuenta o medio exacto se lo indica el asesor al confirmar el pedido.",
  contra_entrega:
    "No manejamos pago contra entrega del pedido: se abona el 50% para iniciar la elaboración y el 50% restante para hacer el envío (o al recoger en fábrica).",
  envios:
    "Sí, tenemos envíos nacionales por cobrar: despachamos por transportadora y el valor del flete se paga al recibir.",
  logo_marca_ropa:
    "No podemos copiar logos comerciales de marcas de ropa deportiva (por ejemplo Nike, Adidas, Puma, Saeta o FSS), para no hacer copias piratas. Las camisetas pueden ser muy parecidas en diseño, y sí sublimamos el logo o escudo de su empresa, de su equipo, de un país u otros gráficos propios que nos envíen.",
  uniforme_incluye:
    "El uniforme incluye camiseta y pantaloneta (en fútbol base también medias).",
};

function sportLabelEs(detected) {
  const d = String(detected || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/^declined:/, "");
  const map = {
    natacion: "natación",
    swimming: "natación",
    ciclismo: "ciclismo",
    cycling: "ciclismo",
    beisbol: "béisbol",
    baseball: "béisbol",
    hockey: "hockey",
    patinaje: "patinaje",
    motocross: "motocross",
    motociclismo: "motociclismo",
    equitacion: "equitación",
    porras: "porras",
    cheer: "porras",
    rugby: "rugby",
    tenis: "tenis",
    padel: "pádel",
    paddle: "pádel",
    waterpolo: "waterpolo",
    handball: "balonmano",
    balonmano: "balonmano",
  };
  return map[d] || d || "ese deporte";
}

function declinedSportReply(sportDetected) {
  const label = sportLabelEs(sportDetected);
  return `Por ahora no fabricamos uniformes de ${label}. Trabajamos ${SPORTS_ALLOWED_ES}.`;
}

/**
 * FAQ no-producto: el agente debe responder con frase fija y NO llamar buscar_producto_odoo.
 * @param {string} text
 * @returns {{ intent: string, customer_reply_es: string, do_not_search: true } | null}
 */
function detectFaqPolicyIntent(text) {
  const t = String(text || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!t) return null;

  // Descuento / mayooreo (antes que "cantidad" genérico de pedido)
  if (
    /\b(descuento|rebaja|rebajar|mayooreo|mayorista)\b/.test(t) ||
    /\bpor\s+(cantidad|volumen)\b/.test(t) ||
    /\b(si\s+(pido|llevo|compro)\s+\d+|por\s+\d+\s*(unidades?|uniformes?))\b/.test(t) &&
      /\b(descuento|rebaja|mas\s+barato|mejor\s+precio)\b/.test(t)
  ) {
    return {
      intent: "descuento",
      customer_reply_es: FIXED_REPLIES.descuento,
      do_not_search: true,
    };
  }

  if (
    /\b(donde\s+estan|donde\s+queda|ubicacion|direccion|punto\s+fisico|me\s+dirijo|me\s+acerco|visita(r)?\s+la\s+fabrica)\b/.test(
      t
    )
  ) {
    return {
      intent: "direccion",
      customer_reply_es: FIXED_REPLIES.direccion,
      do_not_search: true,
    };
  }

  if (
    /\b(catalogo|ver\s+productos|link\s+(de\s+)?(la\s+)?tienda|manda(r)?\s+el\s+catalogo|pagina\s+web\s+de\s+productos)\b/.test(
      t
    )
  ) {
    return {
      intent: "catalogo",
      customer_reply_es: FIXED_REPLIES.catalogo,
      do_not_search: true,
    };
  }

  if (
    /\b(como\s+pago|medios?\s+de\s+pago|transferencia|nequi|cuenta\s+bancaria|a\s+que\s+cuenta)\b/.test(
      t
    ) ||
    (/\babono\b/.test(t) && /\b(como|cual|porcentaje|50\s*%|cincuenta)\b/.test(t))
  ) {
    return {
      intent: "pago",
      customer_reply_es: FIXED_REPLIES.pago,
      do_not_search: true,
    };
  }

  if (
    /\benvios?\s+nacionales?\b/.test(t) ||
    /\bhace(n)?\s+envios?\b/.test(t) ||
    (/\b(envio|envios|despacho|transportadora|flete)\b/.test(t) &&
      /\b(nacional|colombia|medellin|cali|barranquilla|fuera\s+de\s+bogota)\b/.test(t))
  ) {
    return {
      intent: "envios",
      customer_reply_es: FIXED_REPLIES.envios,
      do_not_search: true,
    };
  }

  if (
    /\b(logo|escudo)\b/.test(t) &&
    /\b(nike|adidas|puma|saeta|fss)\b/.test(t)
  ) {
    return {
      intent: "logo_marca_ropa",
      customer_reply_es: FIXED_REPLIES.logo_marca_ropa,
      do_not_search: true,
    };
  }

  if (
    /\b(que\s+incluye|incluye\s+el\s+uniforme|trae\s+pantalon|trae\s+pantaloneta|que\s+trae\s+el\s+uniforme)\b/.test(
      t
    )
  ) {
    return {
      intent: "uniforme_incluye",
      customer_reply_es: FIXED_REPLIES.uniforme_incluye,
      do_not_search: true,
    };
  }

  return null;
}


/**
 * Motor de match producto Life — catálogo semántico + scoring.
 * Usado por odoo_search_product_price (bundled) y tests locales.
 */

function normalizeText(value) {
  return String(value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/dry-fit/g, "dry fit")
    .replace(/[.,;:]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const SPORT_ALIASES = {
  futbol: ["futbol", "football", "soccer", "microfutbol", "micro futbol", "futsal", "futbol sala"],
  baloncesto: ["baloncesto", "basket", "basketball"],
  voleibol: ["voleibol", "voley", "volei", "volley", "volleyball"],
  atletismo: ["atletismo", "track", "pista", "manga sisa"],
};

function detectSport(text) {
  const t = normalizeText(text);
  for (const [sport, aliases] of Object.entries(SPORT_ALIASES)) {
    if (aliases.some((a) => t.includes(normalizeText(a)))) return sport;
  }
  for (const d of SPORT_DECLINED_TERMS) {
    if (t.includes(d)) return `declined:${d}`;
  }
  return null;
}

function detectGarmentType(text, explicit) {
  if (explicit) return explicit;
  const t = normalizeText(text);
  if (/\b(solo|solamente|unicamente)\s+(la\s+)?(camiseta|camisa)\b/.test(t)) return "camiseta_sola";
  if (/\buniformes?\b/.test(t)) return "uniforme_completo";
  if (/\b(conjunto|kit)\b/.test(t) && !/polo y pantalon/.test(t)) return "uniforme_completo";
  if (
    (/\bcamiseta\b|\bcamisa\b/.test(t) && /\bpantaloneta\b|\bshort\b|\bpantalonetas\b/.test(t)) ||
    /\buniforme\s+completo\b/.test(t)
  ) {
    return "uniforme_completo";
  }
  if (/\bcamisetas?\b|\bcamisas?\b/.test(t) && !/\buniforme\b/.test(t)) return "camiseta_sola";
  if (/\bpantaloneta\b|\bshort\b/.test(t)) return "pantaloneta";
  if (/\bmedia\b/.test(t)) return "medias";
  if (/\barquero\b|\bportero\b/.test(t)) return "arquero";
  if (/\brompevientos?\b|\bimpermeable\b/.test(t) && !/\bcamiseta\b|\bpantaloneta\b/.test(t))
    return "chaqueta";
  if (/\bchaquetas?\b/.test(t) && !/\bsudadera\b|\borion\b|\bbuzo\b/.test(t)) return "chaqueta";
  if (/\bsudadera\b|\bbuzo\b|\bbuso\b|\bhoodies?\b/.test(t) && !/\buniforme\b/.test(t))
    return "sudadera_conjunto";
  if (/\bpeto\b|\bpetos\b|\bpechera\b/.test(t)) return "peto";
  if (/\bgorra\b/.test(t)) return "gorra";
  if (/\bbandera\b/.test(t)) return "bandera";
  return null;
}

function inferCollar(text, explicit) {
  if (explicit) return explicit;
  const t = normalizeText(text);
  if (t.includes("polo") && t.includes("boton")) return "polo_con_botones";
  if (t.includes("polo")) return "polo_sin_botones";
  if (t.includes("cuello v") || t.includes("en v")) return "cuello_v";
  if (t.includes("cuello normal")) return "cuello_v";
  if (t.includes("redondo")) return "cuello_redondo";
  if (t.includes("sport")) return "cuello_sport";
  return null;
}

function inferSleeves(text, explicit) {
  if (explicit) return explicit;
  const t = normalizeText(text);
  if (t.includes("manga larga") || t.includes("manga largo")) return "manga_larga";
  if (t.includes("manga sisa") || t.includes("manga siza")) return "manga_sisa";
  if (t.includes("manga china")) return "manga_china";
  if (t.includes("manga corta") || t.includes("manga normal")) return "manga_corta";
  if (t.includes("ranglan") || t.includes("raglan")) return "ranglan";
  return null;
}

function inferMaterial(text, explicit) {
  if (explicit) return explicit;
  const t = normalizeText(text);
  if (t.includes("dumonti") || t.includes("falcao")) return "dumonti";
  if (t.includes("hidrotec")) return "hidrotec";
  if (t.includes("lluvia")) return "lluvia";
  if (t.includes("dry fit") || t.includes("dryfit")) return "dry_fit";
  return null;
}

function inferLining(text, explicit) {
  if (explicit) return explicit;
  const t = normalizeText(text);
  if (/\bcon\s+forro\b/.test(t)) return "con_forro";
  if (/\bsin\s+forro\b/.test(t)) return "sin_forro";
  return null;
}

/**
 * Variantes faltantes: explícito > texto del pedido > foto/referencia.
 * Si la persona lo pidió explícito, gana sobre la foto.
 * Si no hay pedido claro / no especificó, tomar de la foto.
 *
 * @param {{ explicit?: string|null, textBlob?: string, visualBlob?: string, infer: (blob: string, explicit: null) => string|null }} opts
 * @returns {{ value: string|null, source: 'explicit'|'text'|'photo'|null }}
 */
function resolveVariantAttr({ explicit = null, textBlob = "", visualBlob = "", infer }) {
  if (explicit) return { value: explicit, source: "explicit" };
  const fromText = infer(String(textBlob || ""), null);
  if (fromText) return { value: fromText, source: "text" };
  const fromPhoto = infer(String(visualBlob || ""), null);
  if (fromPhoto) return { value: fromPhoto, source: "photo" };
  return { value: null, source: null };
}

function inferShortType(text, sport) {
  const t = normalizeText(text);
  if (t.includes("lycra")) return "lycra";
  if (t.includes("impermeable") || t.includes("microfutbol")) return "impermeable";
  if (t.includes("mariposa") || (sport === "baloncesto" && t.includes("baloncesto"))) return "mariposa";
  if (t.includes("bolsillo")) return "bolsillos";
  return "standard";
}

function materialAliases(material) {
  const m = normalizeText(material);
  if (!m) return [];
  if (m.includes("dumonti") || m.includes("falcao")) return ["dumonti", "falcao"];
  if (m.includes("dry")) return ["dry_fit"];
  return [m.replace(/\s+/g, "_")];
}

function productById(catalog, id) {
  return (catalog?.products || []).find((p) => p.odoo_id === id) || null;
}

function defaultProductForIntent(ctx, catalog) {
  const rules = catalog?.intent_defaults || [];
  const key = [
    ctx.garmentType || "",
    ctx.sport || "",
    ctx.collar || "",
    ctx.sleeves || "",
    ctx.shortType || "",
  ].join("|");
  for (const rule of rules) {
    if (rule.when_sport && ctx.sport !== rule.when_sport) continue;
    if (rule.when_garment && ctx.garmentType !== rule.when_garment) continue;
    if (rule.when_collar && ctx.collar !== rule.when_collar) continue;
    if (rule.when_text_includes?.length) {
      const t = normalizeText(ctx.combinedText);
      if (!rule.when_text_includes.every((x) => t.includes(normalizeText(x)))) continue;
    }
    const p = productById(catalog, rule.odoo_id);
    if (p) return { product: p, reason: rule.reason_es };
  }
  return null;
}

function scoreProduct(product, ctx, catalog) {
  let score = 0;
  const name = normalizeText(product.name);
  const combined = normalizeText(ctx.combinedText);
  const tokens = combined.split(" ").filter((t) => t.length > 2);

  const semantic = (catalog?.product_semantics || {})[String(product.odoo_id)] || {};
  if (semantic.requires_text?.length) {
    const missing = semantic.requires_text.every(
      (req) => !combined.includes(normalizeText(req))
    );
    if (missing) return 0;
  }
  const hasSinCapota = /\bsin\s+capota\b/.test(combined);
  for (const alias of semantic.aliases || []) {
    const a = normalizeText(alias);
    if (hasSinCapota && a.includes("capota")) continue;
    if (a && combined.includes(a)) score += 22;
  }

  if (combined && name.includes(combined)) score += 40;
  if (combined && name.length >= 8 && combined.includes(name)) score += 35;
  for (const token of tokens) {
    if (name.includes(token)) score += 6;
  }

  if (ctx.garmentType === "uniforme_completo" && product.category === "uniforme") score += 25;
  if (ctx.garmentType === "camiseta_sola" && product.category === "camiseta") score += 25;
  if (ctx.garmentType === "camiseta_sola" && product.category === "uniforme") score -= 20;
  if (ctx.garmentType === "uniforme_completo" && product.category === "camiseta") score -= 15;
  if (ctx.garmentType === "sudadera_conjunto") {
    if (name.includes("sudadera") || name.includes("buzo") || name.includes("buso") || name.includes("hoodie"))
      score += 30;
    if (hasSinCapota && name.includes("capota")) score -= 50;
    if (hasSinCapota && (name.includes("sudadera") || name.includes("algodon"))) score += 25;
    if (name.includes("pantalon") && !combined.includes("pantalon") && !name.includes("sudadera")) score -= 25;
    if (name.includes("arquero") && !combined.includes("arquero") && !combined.includes("portero"))
      score -= 50;
    if (product.commercial_role === "extra" && name.includes("chaqueta")) score -= 25;
    if (product.category === "uniforme") score -= 15;
  }
  if (ctx.garmentType === "chaqueta") {
    if (name.includes("chaqueta") && !name.includes("extra") && !name.includes("sudadera")) score += 38;
    if (name.includes("rompeviento") || name.includes("impermeable") || name.includes("lluvia")) score += 12;
    if (/\brompevientos?\b/.test(combined) && name.includes("rompeviento")) score += 40;
    if (/\brompevientos?\b/.test(combined) && name.includes("lotto")) score -= 35;
    if (name.includes("sudadera") && name.includes("pantalon")) score -= 35;
    if (product.category === "uniforme") score -= 25;
    if (product.category === "camiseta") score -= 15;
    const desc = normalizeText(product.description_sale || "");
    if (ctx.withLining === "con_forro" && desc.includes("forro")) score += 14;
    if (ctx.withLining === "sin_forro" && desc.includes("sin forro")) score += 10;
  }
  if (ctx.garmentType === "peto") {
    if (name.includes("peto")) score += 40;
    if (product.category === "uniforme" || product.category === "camiseta") score -= 25;
  }

  if (ctx.sport && (semantic.sports || []).includes(ctx.sport)) score += 18;
  if (ctx.sport === "futbol" && name.includes("futbol")) score += 20;
  if (ctx.sport && product.category === "uniforme" && name.includes(ctx.sport)) score += 15;
  if (ctx.sport === "futbol" && product.category === "uniforme" && !name.includes("futbol")) {
    score -= 10;
  }

  if (ctx.collar === "polo_sin_botones" && product.variant === "polo_sin_botones") score += 20;
  if (ctx.collar === "polo_sin_botones" && product.variant === "polo") score += 15;
  if (ctx.collar?.includes("polo") && name.includes("polo")) score += 15;

  if (ctx.sleeves === "manga_larga" && (name.includes("manga larga") || semantic.sleeves === "manga_larga"))
    score += 15;
  if (ctx.sleeves === "manga_sisa" && (name.includes("atletismo") || ctx.sport === "atletismo")) score += 12;
  if (ctx.sleeves === "manga_corta" && product.variant === "manga_corta") score += 12;

  if (ctx.material) {
    const mats = materialAliases(ctx.material);
    if (mats.includes(product.material) || (ctx.material === "dumonti" && name.includes("dumonti")))
      score += 12;
  }

  if (ctx.shortType === "lycra" && product.variant === "lycra") score += 18;
  if (ctx.shortType === "impermeable" && product.variant === "impermeable") score += 18;
  if (ctx.shortType === "bolsillos" && product.variant === "bolsillos") score += 18;

  for (const cue of ctx.visualCues || []) {
    const c = normalizeText(cue);
    if (c.includes("polo") && name.includes("polo")) score += 25;
    if (c.includes("manga larga") && name.includes("manga larga")) score += 15;
    if (c.includes("voleibol") && name.includes("voleibol")) score += 15;
    if (c.includes("baloncesto") && name.includes("baloncesto")) score += 15;
    if (c.includes("dry fit") && product.material === "dry_fit") score += 8;
  }

  if (semantic.garment_type && ctx.garmentType && semantic.garment_type === ctx.garmentType) score += 10;

  if (product.is_published) score += 10;

  return score;
}

function collectMissingDimensions(ctx) {
  const missing = [];
  if (!ctx.garmentType) missing.push("garment_type");
  if (ctx.garmentType === "uniforme_completo" && !ctx.sport) missing.push("sport");
  if (!ctx.quantityProvided) missing.push("quantity");
  return missing;
}

function buildClarifyingQuestion(ctx, top, second, missingDimensions) {
  if (missingDimensions.includes("garment_type")) {
    return "¿Qué prenda necesita: camiseta, uniforme completo u otra?";
  }
  if (missingDimensions.includes("sport")) {
    return "¿Para qué deporte necesita el uniforme?";
  }
  if (missingDimensions.includes("quantity")) {
    return "¿Cuántas unidades necesita?";
  }
  if (
    ctx.garmentType === "camiseta_sola" &&
    /\bcamisetas?\b|\bcamisas?\b/.test(normalizeText(ctx.productText)) &&
    !/\buniforme\b/.test(normalizeText(ctx.productText))
  ) {
    return null;
  }
  if (ctx.garmentType === "camiseta_sola" && ctx.sport === "futbol") {
    return null;
  }
  if (ctx.collar?.includes("polo") && ctx.garmentType !== "uniforme_completo" && ctx.garmentType !== "camiseta_sola") {
    return "¿La operaria pide camiseta polo sola o uniforme completo con cuello polo?";
  }
  if (top && second && top.score - second.score < 8) {
    return `¿Confirma ${top.product.name} o prefiere ${second.product.name}?`;
  }
  return null;
}

function confidenceFromScores(top, second) {
  if (!top) return "none";
  if (top.score >= 45 && (!second || top.score - second.score >= 12)) return "high";
  if (top.score >= 28 && (!second || top.score - second.score >= 8)) return "medium";
  return "low";
}

/**
 * @param {object} input
 * @param {object} catalog — life_catalog_semantic_v1 (+ products from cache)
 */
function matchProduct(input, catalog) {
  const productText = String(input.product_text || "").trim();
  const variantNotes = String(input.variant_notes || input.comments || "").trim();
  const textBlob = [productText, variantNotes].filter(Boolean).join(" ");
  const visualHints = []
    .concat(input.visual_hints || [], input.photo_description || [], input.reference_notes || [])
    .map(String)
    .filter(Boolean);
  const visualBlob = visualHints.join(" ");
  // combined = texto + foto (para deporte / scoring amplio); attrs usan prioridad.
  const combinedText = [textBlob, visualBlob].filter(Boolean).join(" ");

  const sportRaw =
    input.sport ||
    detectSport(textBlob) ||
    detectSport(visualBlob) ||
    detectSport(combinedText) ||
    null;
  if (sportRaw?.startsWith("declined:")) {
    const sport_detected = sportRaw.replace("declined:", "");
    const customer_reply_es = declinedSportReply(sport_detected);
    return {
      ok: false,
      found: false,
      sport_declined: true,
      sport_detected,
      do_not_search: true,
      message_es: customer_reply_es,
      customer_reply_es,
      agent_hint_es:
        "Política clara: responde ya con customer_reply_es. Prohibido cotizar, buscar_producto_odoo o posponer con el equipo.",
      match_confidence: "none",
      alternatives: [],
    };
  }

  const garmentRes = resolveVariantAttr({
    explicit: input.garment_type || null,
    textBlob,
    visualBlob,
    infer: (blob) => detectGarmentType(blob, null),
  });
  const collarRes = resolveVariantAttr({
    explicit: input.collar || null,
    textBlob,
    visualBlob,
    infer: (blob) => inferCollar(blob, null),
  });
  const sleevesRes = resolveVariantAttr({
    explicit: input.sleeves || null,
    textBlob,
    visualBlob,
    infer: (blob) => inferSleeves(blob, null),
  });
  const materialRes = resolveVariantAttr({
    explicit: input.material || null,
    textBlob,
    visualBlob,
    infer: (blob) => inferMaterial(blob, null),
  });
  const liningRes = resolveVariantAttr({
    explicit: input.with_lining || input.lining || null,
    textBlob,
    visualBlob,
    infer: (blob) => inferLining(blob, null),
  });

  const ctx = {
    productText,
    combinedText,
    quantity: Math.max(1, Number(input.quantity || 1)),
    quantityProvided:
      input.quantity !== undefined &&
      input.quantity !== null &&
      String(input.quantity).trim() !== "",
    sport: sportRaw,
    garmentType: garmentRes.value,
    collar: collarRes.value,
    sleeves: sleevesRes.value,
    material: materialRes.value || "dry_fit",
    withLining: liningRes.value,
    shortType: inferShortType(textBlob || visualBlob, sportRaw),
    visualCues: visualHints,
    attr_sources: {
      garment: garmentRes.source,
      collar: collarRes.source,
      sleeves: sleevesRes.source,
      material: materialRes.source || (materialRes.value ? null : null),
      lining: liningRes.source,
    },
  };
  if (!materialRes.value) ctx.attr_sources.material = materialRes.source || "default";

  const products = catalog?.products || [];
  let scored = products
    .map((product) => ({ product, score: scoreProduct(product, ctx, catalog) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || a.product.list_price_cop - b.product.list_price_cop);

  const defaultPick = defaultProductForIntent(ctx, catalog);
  if (defaultPick && (!scored[0] || scored[0].score < 30)) {
    scored = [{ product: defaultPick.product, score: 38, reason: defaultPick.reason }, ...scored];
  }

  const top = scored[0] || null;
  const second = scored[1] || null;
  const match_confidence = confidenceFromScores(top, second);
  const missing_dimensions = collectMissingDimensions(ctx);
  const clarifying_question = buildClarifyingQuestion(ctx, top, second, missing_dimensions);

  function fmtAttr(label, value, source) {
    if (!value) return null;
    const src =
      source === "photo"
        ? " (foto)"
        : source === "explicit"
          ? " (explícito)"
          : source === "text"
            ? ""
            : source === "default"
              ? " (default)"
              : "";
    return `${label}: ${String(value).replace(/_/g, " ")}${src}`;
  }

  const interpretationParts = [
    ctx.sport ? `deporte: ${ctx.sport}` : null,
    fmtAttr("tipo", ctx.garmentType, ctx.attr_sources.garment),
    fmtAttr("cuello", ctx.collar, ctx.attr_sources.collar),
    fmtAttr("manga", ctx.sleeves, ctx.attr_sources.sleeves),
    fmtAttr("tela", ctx.material, ctx.attr_sources.material),
    fmtAttr("forro", ctx.withLining, ctx.attr_sources.lining),
  ].filter(Boolean);

  const alternatives = scored.slice(0, 5).map((row, idx) => ({
    rank: idx + 1,
    odoo_id: row.product.odoo_id,
    name: row.product.name,
    list_price_cop: row.product.list_price_cop,
    score: row.score,
    reason_es: row.reason || null,
  }));
  const candidates = alternatives.slice(0, 3);

  if (!top) {
    return {
      ok: true,
      found: false,
      match_confidence: "none",
      interpretation_es: interpretationParts.length
        ? `Entendí ${interpretationParts.join(", ")} pero no encontré producto Odoo cercano.`
        : "No encontré producto cercano en catálogo.",
      clarifying_question:
        buildClarifyingQuestion(ctx, null, null, missing_dimensions) ||
        "¿Cómo describe la prenda que necesita?",
      missing_dimensions,
      parsed: ctx,
      attr_sources: ctx.attr_sources,
      candidates: [],
      alternatives: [],
    };
  }

  return {
    ok: true,
    found: true,
    match_confidence,
    odoo_id: top.product.odoo_id,
    odoo_template_id: top.product.odoo_id,
    match_name: top.product.name,
    name: top.product.name,
    category: top.product.category,
    variant: top.product.variant,
    commercial_role: top.product.commercial_role,
    list_price_cop: top.product.list_price_cop,
    unit_cop: top.product.list_price_cop,
    total_cop: top.product.list_price_cop * ctx.quantity,
    interpretation_es: `Propongo: ${top.product.name}${interpretationParts.length ? ` (${interpretationParts.join("; ")})` : ""}.`,
    clarifying_question,
    missing_dimensions,
    parsed: ctx,
    attr_sources: ctx.attr_sources,
    candidates,
    alternatives: alternatives.filter((a) => a.odoo_id !== top.product.odoo_id).slice(0, 4),
  };
}

// <<MATCH_ENGINE_END>>

// <<SHOP_MEDIA_START>>
/**
 * Tienda Odoo — URLs públicas e imágenes para buscar_producto_odoo.
 */

function shopPublicBase(env) {
  return String(env.ODOO_SHOP_PUBLIC_URL || env.ODOO_URL || "")
    .replace(/\/$/, "");
}

function buildProductPageUrl(base, websiteUrl) {
  if (!base) return null;
  if (!websiteUrl) return `${base}/shop`;
  if (/^https?:\/\//i.test(websiteUrl)) return websiteUrl;
  return `${base}${websiteUrl.startsWith("/") ? "" : "/"}${websiteUrl}`;
}

function buildProductImageUrl(base, templateId) {
  if (!base || !templateId) return null;
  return `${base}/web/image/product.template/${templateId}/image_512`;
}

function isShopPhotoRequest(text, input = {}) {
  if (input.include_shop_media === true || input.shop_request === "photos") return true;
  const t = String(text || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  if (!t.trim()) return false;
  return /\b(fotos?|imagenes?|imagen|referencia visual|ver (el )?producto|catalogo|tienda en linea|link de la tienda|pagina web|pagina del producto)\b/.test(
    t
  );
}

function preferPublishedCatalogMatch(local, catalog, preferPublished = false) {
  if (!local?.found || !preferPublished) return local;
  const products = catalog?.products || [];
  const exact = products.find((p) => p.odoo_id === local.odoo_template_id);
  return {
    ...local,
    catalog_published: Boolean(exact?.is_published),
    published_match_switched: false,
  };
}

async function odooRpc(env, params) {
  const resp = await fetch(`${env.ODOO_URL}/jsonrpc`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", method: "call", params }),
  });
  const json = await resp.json();
  if (json?.error) throw new Error(json.error?.message || "Odoo RPC error");
  return json.result;
}

async function odooUid(env) {
  const uid = await odooRpc(env, {
    service: "common",
    method: "authenticate",
    args: [env.ODOO_DB, env.ODOO_USERNAME, env.ODOO_PASSWORD, {}],
  });
  return uid || null;
}

function mapShopRow(env, row) {
  if (!row?.id) return null;
  const base = shopPublicBase(env);
  return {
    id: row.id,
    name: row.name,
    unit_cop: Math.round(Number(row.list_price || 0)),
    is_published: Boolean(row.is_published),
    website_url: row.website_url || null,
    description_sale: row.description_sale || null,
    shop_page_url: buildProductPageUrl(base, row.website_url),
    shop_image_url: buildProductImageUrl(base, row.id),
    shop_home_url: base ? `${base}/shop` : null,
  };
}

async function fetchOdooTemplateLive(env, templateId, fallbackName) {
  try {
    if (!env.ODOO_URL) return null;
    const uid = await odooUid(env);
    if (!uid) return null;
    const rows = await odooRpc(env, {
      service: "object",
      method: "execute_kw",
      args: [
        env.ODOO_DB,
        uid,
        env.ODOO_PASSWORD,
        "product.template",
        "search_read",
        [[["id", "=", templateId], ["sale_ok", "=", true]]],
        {
          fields: [
            "id",
            "name",
            "list_price",
            "is_published",
            "website_url",
            "description_sale",
            "website_sequence",
          ],
          limit: 1,
        },
      ],
    });
    const row = Array.isArray(rows) ? rows[0] : null;
    if (!row?.id) return null;
    const mapped = mapShopRow(env, row);
    if (fallbackName && !mapped.name) mapped.name = fallbackName;
    return mapped;
  } catch {
    return null;
  }
}

async function searchPublishedShopProducts(env, { query = "", limit = 6 } = {}) {
  try {
    if (!env.ODOO_URL) return [];
    const uid = await odooUid(env);
    if (!uid) return [];
    const domain = [
      ["sale_ok", "=", true],
      ["is_published", "=", true],
    ];
    const q = String(query || "").trim();
    if (q && !/^(fotos?|imagenes?|catalogo|tienda)$/i.test(q)) {
      domain.push(["name", "ilike", q]);
    }
    const rows = await odooRpc(env, {
      service: "object",
      method: "execute_kw",
      args: [
        env.ODOO_DB,
        uid,
        env.ODOO_PASSWORD,
        "product.template",
        "search_read",
        [domain],
        {
          fields: ["id", "name", "list_price", "is_published", "website_url", "description_sale"],
          limit: Math.min(Math.max(limit, 1), 12),
          order: "website_sequence asc, name asc",
        },
      ],
    });
    return (Array.isArray(rows) ? rows : []).map((row) => mapShopRow(env, row)).filter(Boolean);
  } catch {
    return [];
  }
}

function normLite(text) {
  return String(text || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

async function fetchVariantExtras(env, templateId) {
  try {
    if (!env.ODOO_URL || !templateId) return [];
    const uid = await odooUid(env);
    if (!uid) return [];
    const rows = await odooRpc(env, {
      service: "object",
      method: "execute_kw",
      args: [
        env.ODOO_DB,
        uid,
        env.ODOO_PASSWORD,
        "product.template.attribute.value",
        "search_read",
        [[["product_tmpl_id", "=", templateId], ["price_extra", ">", 0]]],
        { fields: ["name", "attribute_id", "price_extra"], limit: 40 },
      ],
    });
    return (Array.isArray(rows) ? rows : []).map((r) => ({
      name: r.name,
      attribute: Array.isArray(r.attribute_id) ? r.attribute_id[1] : null,
      extra_cop: Math.round(Number(r.price_extra || 0)),
    }));
  } catch {
    return [];
  }
}

/**
 * Cruza atributos con price_extra de Odoo contra la intención parseada
 * (collar/sleeves/material/shortType) y devuelve solo los sobrecostos pedidos.
 */
function matchRequestedExtras(extras, parsed = {}) {
  if (!Array.isArray(extras) || !extras.length) return [];
  const picked = [];
  const find = (nameRe, attrRe = null) =>
    extras.find(
      (e) =>
        nameRe.test(normLite(e.name)) && (!attrRe || attrRe.test(normLite(e.attribute)))
    );

  const rules = [
    [parsed.withLining === "con_forro", () => find(/con\s*forro/, /forro/)],
    [parsed.sleeves === "manga_larga", () => find(/^larga$/, /manga/)],
    [parsed.collar === "cuello_sport", () => find(/sport|personalizado/, /cuello/)],
    [parsed.material === "dumonti", () => find(/dumonti/, /tela/)],
    [parsed.shortType === "impermeable", () => find(/impermeable/, /pantalon/)],
    [parsed.shortType === "bolsillos", () => find(/bolsillos/, /pantalon/)],
    [parsed.shortType === "lycra", () => find(/licra|lycra/, /pantalon/)],
  ];
  for (const [wanted, get] of rules) {
    if (!wanted) continue;
    const hit = get();
    if (hit && !picked.includes(hit)) picked.push(hit);
  }
  return picked;
}

function compactShopPayload(shop) {
  if (!shop) return null;
  return {
    odoo_template_id: shop.id,
    name: shop.name,
    is_published: shop.is_published,
    page_url: shop.shop_page_url,
    image_url: shop.shop_image_url,
    shop_home_url: shop.shop_home_url,
    description_sale: shop.description_sale,
    unit_cop: shop.unit_cop || null,
  };
}

// <<SHOP_MEDIA_END>>

async function handler(request, env) {
  const body = await request.json().catch(() => ({}));
  const input = body?.input || {};
  const executionVars = body?.execution_context?.vars || body?.vars || {};

  const productText = String(
    input.product_text ||
      input.query ||
      executionVars?.quote?.product_text ||
      executionVars?.intent?.product_text ||
      ""
  ).trim();
  const variantNotes = String(input.variant_notes || "").trim();
  const combinedProductText = [productText, variantNotes].filter(Boolean).join(" ");
  const quantity = Math.max(
    1,
    Number(input.quantity || executionVars?.quote?.quantity || 1)
  );
  const wantsShopMedia = isShopPhotoRequest(productText, input);

  if (!productText && !(input.visual_hints || input.photo_description) && !wantsShopMedia) {
    return json({
      vars: {
        product: { found: false, match_confidence: "none" },
        pricing: null,
      },
      note: "Falta product_text o descripcion visual",
    });
  }

  const matchInput = {
    product_text: combinedProductText || String(input.photo_description || "referencia visual"),
    quantity,
    sport: input.sport || null,
    garment_type: input.garment_type || null,
    collar: input.collar || null,
    sleeves: input.sleeves || null,
    material: input.material || null,
    with_lining: input.with_lining || null,
    visual_hints: []
      .concat(input.visual_hints || [], input.photo_description || [], input.reference_notes || [])
      .filter(Boolean),
  };

  let local = matchProduct(matchInput, SEMANTIC_CATALOG);
  local = preferPublishedCatalogMatch(local, SEMANTIC_CATALOG, wantsShopMedia);

  if (local.sport_declined) {
    return json({
      status: "blocked",
      message: local.customer_reply_es || local.message_es,
      vars: {
        product: {
          found: false,
          match_confidence: "none",
          sport_declined: true,
          sport_detected: local.sport_detected || null,
          customer_reply_es: local.customer_reply_es || local.message_es,
          do_not_search: true,
          agent_hint_es: local.agent_hint_es || null,
        },
        service: serviceMeta("blocked", local.customer_reply_es || local.message_es),
      },
    });
  }

  let unit = local.unit_cop;
  let matchName = local.match_name;
  let matchId = local.odoo_template_id;
  let priceSource = "catalog_cache";
  let shop = null;
  let shopCatalog = [];

  const odooCreds = {
    ODOO_URL: env.ODOO_URL,
    ODOO_DB: env.ODOO_DB,
    ODOO_USERNAME: env.ODOO_USERNAME,
    ODOO_PASSWORD: env.ODOO_PASSWORD,
  };

  let variantExtras = [];

  if (odooCreds.ODOO_URL) {
    if (local.found && matchId) {
      const live = await fetchOdooTemplateLive(odooCreds, matchId, matchName);
      if (live) {
        shop = live;
        if (live.unit_cop) {
          unit = live.unit_cop;
          matchName = live.name || matchName;
          matchId = live.id || matchId;
          priceSource = "odoo_live";
        }
      }
      const wantsVariant =
        local.parsed &&
        (local.parsed.withLining === "con_forro" ||
          local.parsed.sleeves === "manga_larga" ||
          local.parsed.collar === "cuello_sport" ||
          local.parsed.material === "dumonti" ||
          ["impermeable", "bolsillos", "lycra"].includes(local.parsed.shortType));
      if (wantsVariant) {
        const extras = await fetchVariantExtras(odooCreds, matchId);
        variantExtras = matchRequestedExtras(extras, local.parsed);
        if (variantExtras.length && unit) {
          unit += variantExtras.reduce((s, e) => s + e.extra_cop, 0);
        }
      }
    }

    if (wantsShopMedia) {
      if (!local.found) {
        shopCatalog = await searchPublishedShopProducts(odooCreds, {
          query: productText,
          limit: Number(input.shop_catalog_limit || 5),
        });
      }
    }
  }

  // --- Jev Layer: Desambiguación de producto y sobrecostos de tallas ---
  const JEV_MODE = String(env?.LIFE_JEV_MODE || "off").toLowerCase().trim();
  const JEV_THRESHOLD = Number(env?.LIFE_JEV_THRESHOLD || 0.7);
  let jevShadow = null;
  let sizeSurcharges = [];

  if (JEV_MODE === "shadow" || JEV_MODE === "on") {
    const t0 = Date.now();
    const key = String(env?.OPENROUTER_API_KEY || "").trim();
    if (key) {
      const jevQuestions = {
        matched_template: {
          type: "choice",
          instructions: "De los templates del catálogo de Life Deportes, ¿cuál es el producto principal solicitado? 115 para Uniforme de Fútbol completo (camiseta+pantaloneta), 62 para Camiseta dry-fit sola, 23 para Baloncesto, 31 para Voleibol, 8 para Polo presentación, 68 para Rompevientos, 1800 para Chaqueta Lotto, 66 para Sudadera, 179 para Buzo arquero, 178 para Conjunto arquero, 69 para Peto.",
          criteria: {
            "115": "Uniforme de Fútbol completo (camiseta + pantaloneta + medias)",
            "62": "Camiseta deportiva dry-fit (solo camiseta)",
            "23": "Uniforme de baloncesto",
            "31": "Uniforme de voleibol",
            "8": "Uniforme de Presentación polo",
            "68": "Chaqueta rompevientos",
            "1800": "Chaqueta Lotto",
            "66": "Sudadera Chaqueta y Pantalón",
            "179": "Buzo de arquero",
            "178": "Conjunto de arquero",
            "69": "Peto sublimado",
            "other": "Otro producto o no especificado claramente"
          }
        },
        collar_type: {
          type: "choice",
          instructions: "¿El cliente solicita cuello polo o cuello sport (+ $3.000 COP)?",
          criteria: {
            "sport_polo": "Solicita cuello polo o cuello sport",
            "normal": "Cuello en V, redondo o normal",
            "unspecified": "No especifica cuello"
          }
        },
        has_plus_sizes: {
          type: "choice",
          instructions: "¿El pedido contiene prendas en tallas especiales (2XL / XXL o 3XL / XXXL)? Recuerda: 2XL y XXL son sinónimos exactos (+$5.000 COP); 3XL y XXXL son sinónimos exactos (+$10.000 COP).",
          criteria: {
            "none": "No hay tallas especiales o solo tallas estándar 2 a XL",
            "has_2xl": "Tiene talla 2XL o XXL",
            "has_3xl": "Tiene talla 3XL o XXXL",
            "has_both": "Tiene tanto 2XL/XXL como 3XL/XXXL"
          }
        },
        qty_2xl: {
          type: "choice",
          instructions: "¿Cuántas prendas en talla 2XL o XXL solicita el cliente? (2XL y XXL son sinónimos)",
          criteria: {
            "0": "Cero prendas en 2XL o XXL",
            "1": "Una prenda en 2XL o XXL",
            "2": "Dos prendas en 2XL o XXL",
            "3": "Tres prendas en 2XL o XXL",
            "4": "Cuatro prendas en 2XL o XXL",
            "5": "Cinco prendas en 2XL o XXL",
            "6": "Seis prendas en 2XL o XXL",
            "7": "Siete prendas en 2XL o XXL",
            "8": "Ocho prendas en 2XL o XXL",
            "9": "Nueve prendas en 2XL o XXL",
            "10": "Diez prendas en 2XL o XXL",
            "more_than_10": "Más de 10 prendas en 2XL o XXL"
          }
        },
        qty_3xl: {
          type: "choice",
          instructions: "¿Cuántas prendas en talla 3XL o XXXL solicita el cliente? (3XL y XXXL son sinónimos)",
          criteria: {
            "0": "Cero prendas en 3XL o XXXL",
            "1": "Una prenda en 3XL o XXXL",
            "2": "Dos prendas en 3XL o XXXL",
            "3": "Tres prendas en 3XL o XXXL",
            "4": "Cuatro prendas en 3XL o XXXL",
            "5": "Cinco prendas en 3XL o XXXL",
            "6": "Seis prendas en 3XL o XXXL",
            "7": "Siete prendas en 3XL o XXXL",
            "8": "Ocho prendas en 3XL o XXXL",
            "9": "Nueve prendas en 3XL o XXXL",
            "10": "Diez prendas en 3XL o XXXL",
            "more_than_10": "Más de 10 prendas en 3XL o XXXL"
          }
        }
      };

      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), 8000);
      try {
        const jevRes = await fetch("https://openrouter.ai/api/alpha/decisions", {
          method: "POST",
          headers: {
            Authorization: "Bearer " + key,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: "typesafe/jev-1.13",
            state: {
              customer_text: combinedProductText,
              quantity,
              local_match: { id: matchId, name: matchName, score: local.score },
            },
            questions: jevQuestions,
          }),
          signal: ctrl.signal,
        });
        clearTimeout(timer);

        if (jevRes.ok) {
          const jevJson = await jevRes.json();
          const ans = jevJson?.answers || {};
          const matchedChoice = ans.matched_template?.choice;
          const matchedConf = Number(ans.matched_template?.confidence || 0);
          const collarChoice = ans.collar_type?.choice;
          const qty2XL = parseInt(ans.qty_2xl?.choice || "0", 10) || 0;
          const qty3XL = parseInt(ans.qty_3xl?.choice || "0", 10) || 0;

          let jevApplied = false;

          // Sobrecostos de tallas
          if (qty2XL > 0) {
            sizeSurcharges.push({
              odoo_product_id: 1805,
              type: "size_2xl",
              name: "Sobrecosto Talla 2XL / XXL",
              unit_cop: 5000,
              quantity: qty2XL,
              total_cop: 5000 * qty2XL,
            });
          }
          if (qty3XL > 0) {
            sizeSurcharges.push({
              odoo_product_id: 1806,
              type: "size_3xl",
              name: "Sobrecosto Talla 3XL / XXXL",
              unit_cop: 10000,
              quantity: qty3XL,
              total_cop: 10000 * qty3XL,
            });
          }
          if (collarChoice === "sport_polo" && matchId !== 8 && matchId !== 61) {
            sizeSurcharges.push({
              type: "collar",
              name: "Sobrecosto Cuello Polo/Sport",
              unit_cop: 3000,
              quantity: quantity,
              total_cop: 3000 * quantity,
            });
          }

          if (JEV_MODE === "on" && matchedChoice && matchedChoice !== "other" && matchedConf >= JEV_THRESHOLD) {
            const tmplNum = Number(matchedChoice);
            if (Number.isFinite(tmplNum) && tmplNum > 0) {
              matchId = tmplNum;
              if (tmplNum === 115) { matchName = "Uniforme de Fútbol"; unit = 50000; }
              else if (tmplNum === 62) { matchName = "Camiseta deportiva dry-fit"; unit = 30000; }
              else if (tmplNum === 23) { matchName = "Uniforme de baloncesto"; unit = 50000; }
              else if (tmplNum === 31) { matchName = "Uniforme de voleibol"; unit = 50000; }
              else if (tmplNum === 66) { matchName = "Sudadera Chaqueta y Pantalón"; unit = 100000; }
              else if (tmplNum === 8) { matchName = "Uniforme de Presentación polo"; unit = 75000; }
              else if (tmplNum === 68) { matchName = "Chaqueta rompevientos"; unit = 60000; }
              else if (tmplNum === 1800) { matchName = "Chaqueta Lotto"; unit = 60000; }
              else if (tmplNum === 1795) { matchName = "Buso deportivo"; unit = 65000; }
            }
            const hasSinCapota = /sins+capota/i.test(combinedProductText);
            if (hasSinCapota && matchName) {
              matchName = matchName.replace(/s*cons+capota/i, "") + " (sin capota)";
            }
            jevApplied = true;
          }

          jevShadow = {
            enabled: true,
            mode: JEV_MODE,
            ok: true,
            matched_template: matchedChoice,
            confidence: matchedConf,
            collar: collarChoice,
            qty_2xl: qty2XL,
            qty_3xl: qty3XL,
            surcharges_count: sizeSurcharges.length,
            applied: JEV_MODE === "on",
            latency_ms: Date.now() - t0,
            cost_usd: jevJson?.usage?.cost || null,
          };
        } else {
          jevShadow = { enabled: true, mode: JEV_MODE, ok: false, reason: "http_" + jevRes.status };
        }
      } catch (err) {
        clearTimeout(timer);
        jevShadow = { enabled: true, mode: JEV_MODE, ok: false, reason: err?.name === "AbortError" ? "timeout" : "network" };
      }
    }
  }

  const surchargesTotal = (JEV_MODE === "on" ? sizeSurcharges : []).reduce((s, x) => s + x.total_cop, 0);
  const total = unit ? (unit * quantity) + surchargesTotal : null;

  // Resumen formateado para que el bot lo cite directamente
  let summaryForBot = "";
  if (unit) {
    const parts = [quantity + " × " + matchName + " ($" + Number(unit).toLocaleString("es-CO") + " c/u)"];
    if (sizeSurcharges.length > 0) {
      const extraList = sizeSurcharges
        .map(function(s) { return s.quantity + " u. " + s.name + " (+$" + Number(s.total_cop).toLocaleString("es-CO") + ")"; })
        .join(", ");
      parts.push("Sobrecostos: " + extraList);
    }
    parts.push("Total pedido: $" + Number(total).toLocaleString("es-CO") + " COP");
    summaryForBot = parts.join(". ") + ".";
  }

  let status = local.found ? "ready" : "needs_clarification";
  if (wantsShopMedia && shop?.is_published) status = "shop_media_ready";
  else if (wantsShopMedia && shopCatalog.length) status = "shop_catalog_suggestions";
  else if (wantsShopMedia && local.found)
    status = "shop_not_published";

  const shopPayload = compactShopPayload(shop?.is_published ? shop : null);
  const catalogPayload = shopCatalog.map((row) => compactShopPayload(row)).filter(Boolean);
  const shopBase = shopPublicBase(odooCreds);
  const unavailableShopPayload =
    wantsShopMedia && local.found && !shopPayload
      ? {
          odoo_template_id: matchId || null,
          name: matchName || null,
          is_published: false,
          page_url: null,
          image_url: null,
          shop_home_url: shopBase ? `${shopBase}/shop` : null,
          unavailable_reason: "exact_product_not_published",
        }
      : null;

  return json({
    status,
    message:
      wantsShopMedia && shopPayload?.page_url
        ? `Tienda: ${shopPayload.name} — ${shopPayload.page_url}`
        : wantsShopMedia && local.found
          ? "El producto exacto no tiene una foto publicada en Odoo."
        : summaryForBot || local.interpretation_es || (local.found ? matchName : "Sin match"),
    vars: {
      product: {
        found: Boolean(local.found),
        match_confidence: local.match_confidence,
        match_name: matchName || null,
        match_id: matchId || null,
        odoo_template_id: matchId || null,
        query_text: productText,
        interpretation_es: local.interpretation_es || null,
        clarifying_question: local.clarifying_question || null,
        missing_dimensions: local.missing_dimensions || [],
        candidates: local.candidates || [],
        parsed_intent: local.parsed || null,
        alternatives: local.alternatives || [],
        category: local.category || null,
        variant: local.variant || null,
        commercial_role: local.commercial_role || null,
        catalog_published: shop?.is_published ?? null,
      },
      shop: shopPayload || unavailableShopPayload,
      shop_catalog: catalogPayload,
      pricing: unit
        ? {
            unit_cop: unit,
            total_cop: total,
            base_subtotal: unit * quantity,
            quantity,
            price_source: priceSource,
            variant_extras: variantExtras,
            surcharges: sizeSurcharges,
            summary_es: summaryForBot,
          }
        : null,
      quote: local.found
        ? {
            product_text: matchName,
            quantity,
            unit_cop: unit,
            total_cop: total,
            odoo_product_id: matchId,
            match_confidence: local.match_confidence,
            price_source: priceSource,
            surcharges: sizeSurcharges,
            summary_es: summaryForBot,
          }
        : {
            product_text: productText,
            quantity,
            match_confidence: local.match_confidence,
          },
      jev_shadow: jevShadow,
      service: serviceMeta(status),
    },
  });
}

function json(payload) {
  return new Response(JSON.stringify(payload), {
    headers: { "Content-Type": "application/json" },
  });
}

function serviceMeta(status, fallback = null) {
  return {
    last_call_name: "buscar_producto_odoo",
    last_call_status: status,
    last_call_at: new Date().toISOString(),
    fallback_message: fallback,
  };
}
