// AUTO-GENERATED by bundle_staff_complete_order.js
/**
 * Contrato staff pedido completo: resolved_lines, fingerprint, cross-check, readiness.
 */

const SCHEMA_PEOPLE = "life_order_people_v1";
const WRITE_READY = "ready";
const WRITE_NEEDS_CONFIRMATION = "needs_staff_confirmation";
const WRITE_BLOCKED = "blocked";
const WRITE_NEEDS_RECONCILE = "needs_human_reconcile";

const ATTR_KEYS = [
  "cuello",
  "tela",
  "manga",
  "tipo_pantalon",
  "medias",
  "forro",
  "deporte",
  "genero",
];
const KNOWN_ATTR_SET = new Set(ATTR_KEYS);

/** Columnas principales del Formulario (ADR 0003). */
const PRINCIPAL_ATTR_KEYS = ["cuello", "manga", "genero", "deporte"];
const PRINCIPAL_ATTR_SET = new Set(PRINCIPAL_ATTR_KEYS);

/** Etiquetas para concatenar en «Otros atributos». */
const OTROS_ATTR_LABELS = {
  tela: "Tela",
  medias: "Medias",
  tipo_pantalon: "Pantaloneta",
  forro: "Forro",
  tipo_manga: "Tipo de Manga",
  color: "Color",
  bordado: "Bordado",
  botones: "Botones",
  cremallera: "Cremallera",
  tipo_camiseta: "Tipo de camiseta",
  tallas: "Tallas",
  telas: "telas",
};

/** @deprecated usar PRINCIPAL_ATTR_KEYS — alias compat */
const SPREADSHEET_ATTR_COLS = PRINCIPAL_ATTR_KEYS;

function compact(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim();
}

/** Separa display name Odoo en producto base + atributos embebidos en paréntesis. */
function splitProductDisplayName(displayName) {
  const raw = compact(displayName);
  if (!raw) return { product_base: "", embedded_attrs: {}, unknown_parts: [], raw: "" };

  // Odoo a menudo concatena descripción ecommerce tras el cierre: "Base (attrs) Largo texto…"
  let product_base = raw;
  let attrsBlob = "";
  const withTrail = raw.match(/^(.+?)\s*\(([^)]+)\)\s*(.*)$/);
  if (withTrail) {
    product_base = compact(withTrail[1]);
    attrsBlob = withTrail[2];
    const trailing = compact(withTrail[3]);
    // Si el trailing parece descripción larga (no atributo corto), se ignora como base
    if (trailing && trailing.length < 40 && !/\s{2,}/.test(trailing)) {
      // raro: texto corto tras ) — no lo usamos como base
    }
  } else {
    return { product_base: raw, embedded_attrs: {}, unknown_parts: [], raw };
  }

  const embedded_attrs = {};
  const unknown_parts = [];
  for (const part of attrsBlob.split(",")) {
    const token = compact(part);
    if (!token) continue;
    const lower = token.toLowerCase();
    if (/cuello|polo|redondo|\bv\b/.test(lower)) embedded_attrs.cuello = token;
    else if (/dry|dumonti|hidrotec|lluvia|tela/.test(lower)) embedded_attrs.tela = token;
    else if (/manga|sisa|ranglan|china|corta|larga/.test(lower) && !/media/.test(lower)) {
      embedded_attrs.manga = token;
    } else if (/media/.test(lower)) embedded_attrs.medias = token;
    else if (/pantalon|lycra|short|mariposa/.test(lower)) embedded_attrs.tipo_pantalon = token;
    else if (/forro/.test(lower)) embedded_attrs.forro = token;
    else if (/^masc|^fem|g[eé]nero/.test(lower)) embedded_attrs.genero = token;
    else if (/deporte|f[uú]tbol|voleibol|baloncesto|atletismo/.test(lower)) {
      embedded_attrs.deporte = token;
    }
    else unknown_parts.push(token);
  }
  return { product_base, embedded_attrs, unknown_parts, raw };
}

/**
 * Producto base + principales + Otros atributos (concat) + Comentario (persona/residual).
 */
function decomposeProductForSpreadsheet(
  displayName,
  attributes = {},
  existingComments = ""
) {
  const split = splitProductDisplayName(displayName);
  const merged = {
    ...split.embedded_attrs,
    ...normalizeAttributes(attributes),
  };
  const principal = {};
  const otrosParts = [];
  const commentParts = [];

  for (const [key, val] of Object.entries(merged)) {
    const v = compact(val);
    if (!v) continue;
    if (key === "extra") {
      commentParts.push(v);
      continue;
    }
    if (PRINCIPAL_ATTR_SET.has(key)) {
      principal[key] = v;
      continue;
    }
    const label = OTROS_ATTR_LABELS[key] || (KNOWN_ATTR_SET.has(key) ? key : null);
    if (label) otrosParts.push(`${label}: ${v}`);
    else commentParts.push(`${key}: ${v}`);
  }
  for (const part of split.unknown_parts || []) {
    const p = compact(part);
    if (p) commentParts.push(p);
  }
  const personComment = compact(existingComments);
  if (personComment) commentParts.unshift(personComment);

  const otros_atributos = [...new Set(otrosParts)].join(" · ");
  const comments = [...new Set(commentParts)].join(" · ");

  return {
    product_base: split.product_base || compact(displayName),
    principal,
    attributes: { ...principal }, // compat: solo principales tipados en columns
    otros_atributos,
    comments,
    raw: split.raw,
  };
}

/** Normaliza atributos desde match engine / Odoo PTAV / texto libre. */
function normalizeAttributes(source = {}) {
  const out = {};
  const map = {
    cuello: ["cuello", "collar", "neck"],
    tela: ["tela", "material", "fabric"],
    manga: ["manga", "sleeves", "sleeve", "largo_manga", "largo manga"],
    tipo_pantalon: ["tipo_pantalon", "short_style", "short_type", "pantalon"],
    medias: ["medias", "socks", "media"],
    forro: ["forro", "lining"],
    deporte: ["deporte", "deportes", "sport", "disciplina"],
    genero: ["genero", "género", "gender", "sex"],
  };
  for (const [canon, aliases] of Object.entries(map)) {
    for (const key of aliases) {
      const val = source[key];
      if (val != null && compact(val)) {
        out[canon] = compact(val);
        break;
      }
    }
  }
  return out;
}

function attributesFromOdooPtavs(ptavs = []) {
  const out = {};
  for (const ptav of ptavs) {
    const attrName = compact(ptav?.attribute_id?.[1] || ptav?.attribute_name || "").toLowerCase();
    const value = compact(ptav?.name || ptav?.value || "");
    if (!value) continue;
    if (/cuello/.test(attrName)) out.cuello = value;
    else if (/tela/.test(attrName)) out.tela = value;
    else if (/largo\s*manga|manga/.test(attrName)) out.manga = value;
    else if (/pantalon/.test(attrName)) out.tipo_pantalon = value;
    else if (/medias|media/.test(attrName)) out.medias = value;
    else if (/forro/.test(attrName)) out.forro = value;
    else if (/deporte/.test(attrName)) out.deporte = value;
    else if (/g[eé]nero|genero/.test(attrName)) out.genero = value;
  }
  return out;
}

function buildResolvedLine(input = {}, index = 0) {
  const productText = compact(input.product_text || input.name || "");
  const split = splitProductDisplayName(input.display_name || productText);
  const attributes = {
    ...split.embedded_attrs,
    ...normalizeAttributes(input.attributes || input.product_attributes || {}),
    ...normalizeAttributes(input),
  };
  const qty = Math.max(0, Number(input.quantity || input.product_uom_qty || 0));
  const confidence = compact(input.confidence || input.match_confidence || "");
  const lineId =
    compact(input.line_id) ||
    `rl_${index + 1}_${String(input.product_variant_id || input.odoo_product_id || productText)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .slice(0, 40)}`;

  return {
    line_id: lineId,
    product_text: productText || split.product_base,
    product_base: compact(input.product_base) || split.product_base || productText,
    product_tmpl_id: Number(input.product_tmpl_id || 0) || null,
    product_variant_id:
      Number(input.product_variant_id || input.odoo_product_id || input.product_id || 0) || null,
    attributes,
    quantity: qty,
    unit_cop: Number(input.unit_cop || input.unit_price || input.price_unit || 0) || null,
    confidence,
    category: compact(input.category || "").toLowerCase() || null,
    commercial_role: compact(input.commercial_role || "") || null,
    comments: compact(input.comments || input.variant_notes || input.comment || ""),
    alternatives: Array.isArray(input.alternatives) ? input.alternatives : [],
    clarifying_question: compact(input.clarifying_question || "") || null,
  };
}

function resolvedLinesFromCommercial(lines = []) {
  return (lines || []).map((line, i) => buildResolvedLine(line, i));
}

function draftRowsFromResolvedLines(resolvedLines = []) {
  return (resolvedLines || [])
    .filter((line) => Number(line.product_variant_id || 0) > 0 && Number(line.quantity || 0) > 0)
    .map((line) => ({
      product_id: line.product_variant_id,
      name: line.product_base || line.product_text,
      quantity: line.quantity,
      unit_price: line.unit_cop || 0,
      line_id: line.line_id,
      attributes: line.attributes,
      comments: line.comments,
    }));
}

function peopleCount(detail = {}) {
  if (Array.isArray(detail.people) && detail.people.length) return detail.people.length;
  if (Array.isArray(detail.rows) && detail.rows.length) return detail.rows.length;
  return Number(detail.person_count || 0) || 0;
}

function peopleForSpreadsheet(detail = {}) {
  if (Array.isArray(detail.people) && detail.people.length) {
    return detail.people.map((person, i) => {
      const identity = person.identity || {};
      const components = Array.isArray(person.components) ? person.components : [];
      const primary = components[0] || {};
      const comments = [
        compact(person.comments),
        compact(primary.comment),
        primary.goalkeeper ? "Arquero" : "",
        compact(primary.sleeve || primary.manga),
      ]
        .filter(Boolean)
        .join(" · ");
      return {
        person_id: person.person_id || `p${i + 1}`,
        nombre: compact(identity.print_name || identity.display_name || ""),
        numero: compact(identity.number || ""),
        talla: compact(primary.size || ""),
        color_medias: compact(person.color_medias || primary.color_medias || ""),
        manga: compact(primary.sleeve || primary.manga || ""),
        genero: compact(person.identity?.group || person.grupo || identity.group || ""),
        grupo: compact(person.identity?.group || person.grupo || identity.group || ""),
        comentarios: comments,
        product_line_key: compact(primary.product_line_key || person.product_line_key || ""),
        resolved_line_id: compact(primary.resolved_line_id || person.resolved_line_id || ""),
      };
    });
  }
  return (detail.rows || []).map((row, i) => ({
    person_id: `r${i + 1}`,
    nombre: compact(row.nombre || row.nombre_uniforme || ""),
    numero: compact(row.numero || ""),
    talla: compact(row.talla || ""),
    color_medias: compact(row.color_medias || row.medias || ""),
    manga: compact(row.manga || ""),
    genero: compact(row.genero || row.grupo || ""),
    grupo: compact(row.grupo || row.genero || ""),
    comentarios: [
      compact(row.comentario || row.rol || ""),
      row.arquero ? "Arquero" : "",
    ]
      .filter(Boolean)
      .join(" · "),
    product_line_key: compact(row.product_line_key || row.section_key || ""),
    resolved_line_id: compact(row.resolved_line_id || ""),
  }));
}

/**
 * Cruza personas del detalle vs cantidades de líneas resueltas.
 * Diseño ($0) se ignora.
 */
function crossCheckPeopleVsLines({ detail = {}, resolvedLines = [] } = {}) {
  const people = peopleForSpreadsheet(detail);
  const productLines = (resolvedLines || []).filter(
    (line) =>
      Number(line.quantity || 0) > 0 &&
      !/dise[nñ]o/i.test(line.product_base || line.product_text || "")
  );
  const totalQty = productLines.reduce((s, l) => s + Number(l.quantity || 0), 0);
  const personCount = people.length;
  const mismatches = [];

  if (productLines.length && personCount && personCount !== totalQty) {
    mismatches.push({
      code: "qty_people_vs_lines",
      message: `Personas en lista (${personCount}) ≠ suma de líneas (${totalQty})`,
      person_count: personCount,
      line_qty: totalQty,
    });
  }

  const linked = people.filter((p) => p.resolved_line_id || p.product_line_key);
  if (linked.length) {
    const byLine = {};
    for (const p of linked) {
      const key = p.resolved_line_id || p.product_line_key;
      byLine[key] = (byLine[key] || 0) + 1;
    }
    for (const line of productLines) {
      const key = line.line_id;
      const count = byLine[key] || byLine[line.product_text] || 0;
      if (count && count !== Number(line.quantity || 0)) {
        mismatches.push({
          code: "line_person_qty",
          line_id: key,
          message: `Línea ${line.product_base}: ${count} personas vs qty ${line.quantity}`,
          person_count: count,
          line_qty: line.quantity,
        });
      }
    }
  }

  const status = mismatches.length ? "mismatch" : personCount || totalQty ? "complete" : "empty";
  return {
    status,
    ok: mismatches.length === 0,
    person_count: personCount,
    line_qty: totalQty,
    mismatches,
  };
}

function stableFingerprint(payload = {}) {
  const lines = (payload.resolved_lines || payload.commercial_lines || [])
    .map((l) => ({
      p: Number(l.product_variant_id || l.odoo_product_id || 0) || compact(l.product_text || l.name),
      q: Number(l.quantity || 0),
      a: normalizeAttributes(l.attributes || l),
    }))
    .sort((a, b) => String(a.p).localeCompare(String(b.p)));
  const people = peopleForSpreadsheet(payload.detail || {})
    .map((p) => `${p.numero}|${p.nombre}|${p.talla}`)
    .sort();
  return JSON.stringify({ lines, people, partner: compact(payload.partner_key || "") });
}

/**
 * Evalúa si el borrador staff puede escribirse en Odoo.
 * @returns {{ status, code, message, fingerprint, resolved_lines, cross_check }}
 */
function evaluateStaffWriteReadiness(vars = {}) {
  const orderDraft = vars.order_draft || {};
  const quote = vars.quote || {};
  const staff = vars.staff || {};

  let resolved = Array.isArray(orderDraft.commercial?.resolved_lines)
    ? orderDraft.commercial.resolved_lines.map((l, i) => buildResolvedLine(l, i))
    : [];

  if (!resolved.length && Array.isArray(orderDraft.commercial?.lines)) {
    resolved = resolvedLinesFromCommercial(orderDraft.commercial.lines);
  }

  if (!resolved.length && compact(quote.product_text)) {
    resolved = [
      buildResolvedLine(
        {
          product_text: quote.product_text,
          quantity: quote.quantity,
          product_variant_id: quote.odoo_product_id,
          confidence: quote.match_confidence,
          attributes: quote.product_attributes,
          category: /uniforme/i.test(quote.product_text) ? "uniforme" : null,
        },
        0
      ),
    ];
  }

  if (!resolved.length) {
    return {
      status: WRITE_BLOCKED,
      code: "no_lines",
      message: "Pedido incompleto: sin líneas comerciales.",
      fingerprint: null,
      resolved_lines: [],
      cross_check: null,
    };
  }

  const baseUniformQty = resolved
    .filter((l) => l.category === "uniforme" || /uniforme/i.test(l.product_text || ""))
    .reduce((s, l) => s + Number(l.quantity || 0), 0);
  if (baseUniformQty > 0 && baseUniformQty < 6) {
    return {
      status: WRITE_BLOCKED,
      code: "min_uniform",
      message: "Pedido incompleto: minimo 6 uniformes del mismo diseno.",
      fingerprint: null,
      resolved_lines: resolved,
      cross_check: null,
    };
  }

  const standalone = resolved.filter(
    (l) => l.category !== "uniforme" && !/uniforme/i.test(l.product_text || "")
  );
  if (baseUniformQty === 0) {
    const below = standalone.find((l) => Number(l.quantity || 0) < 6);
    if (below) {
      return {
        status: WRITE_BLOCKED,
        code: "min_standalone",
        message: `Pedido mínimo 6 unidades de ${below.product_base || below.product_text}.`,
        fingerprint: null,
        resolved_lines: resolved,
        cross_check: null,
      };
    }
  }

  const fingerprint = stableFingerprint({
    resolved_lines: resolved,
    detail: orderDraft.detail,
    partner_key:
      quote.customer_wa_id ||
      quote.customer_display_name ||
      quote.order_or_team_name_for_billing ||
      "",
  });

  const unresolved = resolved.filter((l) => !Number(l.product_variant_id || 0));
  const ambiguous = resolved.filter((l) =>
    ["low", "none", "medium"].includes(String(l.confidence || ""))
  );
  const parseStatus = compact(orderDraft.detail?.parse_status || "");
  const hasWarnings =
    Boolean(orderDraft.blockers?.length) ||
    Boolean(orderDraft.detail?.warnings?.length) ||
    parseStatus === "partial" ||
    parseStatus === "needs_review";

  const confirmed =
    compact(staff.confirmation_fingerprint) &&
    compact(staff.confirmation_fingerprint) === fingerprint;

  const compiledAmbiguity =
    ambiguous.length > 0 ||
    (unresolved.length > 0 &&
      resolved.some((l) => String(l.confidence || "") === "high"));

  if ((compiledAmbiguity || hasWarnings) && !confirmed) {
    const summary = resolved
      .map(
        (l) =>
          `• ${l.product_base || l.product_text} × ${l.quantity}` +
          (l.product_variant_id ? "" : " (sin variante Odoo)") +
          (l.confidence && l.confidence !== "high" ? ` [${l.confidence}]` : "")
      )
      .join("\n");
    return {
      status: WRITE_NEEDS_CONFIRMATION,
      code: "needs_confirmation",
      message: `Hay ambigüedad o parseo parcial. Resumen:\n${summary}\nResponde CONFIRMO SUBIR para crear el borrador.`,
      fingerprint,
      resolved_lines: resolved,
      cross_check: null,
    };
  }

  if (confirmed && unresolved.length) {
    return {
      status: WRITE_BLOCKED,
      code: "unresolved_variant",
      message: `Falta variante Odoo exacta para: ${unresolved.map((l) => l.product_text).join(", ")}`,
      fingerprint,
      resolved_lines: resolved,
      cross_check: null,
    };
  }

  const cross = crossCheckPeopleVsLines({
    detail: orderDraft.detail,
    resolvedLines: resolved,
  });

  return {
    status: WRITE_READY,
    code: "pedido_ready",
    message: null,
    fingerprint,
    resolved_lines: resolved,
    cross_check: cross,
  };
}

function spreadsheetStateFromCross(cross, spreadsheetId = null) {
  return {
    id: spreadsheetId,
    status: cross?.status || "empty",
    fingerprint: null,
    cross_check: cross || null,
  };
}



/**
 * Formulario Life — fill nativo Odoo 19.
 *
 * NO pisa fórmulas en Productos del pedido A–F ni Aprobación A–B (SEQUENCE / XLOOKUP / ODOO.LIST).
 * Renombra pestaña Pedido → Productos del pedido.
 * Columnas principales + Otros atributos + Comentario (ADR 0003 / 0004).
 */

const PRODUCTOS_SHEET_NAME = "Productos del pedido";
const PRODUCTOS_SHEET_RE = /^(pedido|productos del pedido)$/i;

/**
 * Productos del pedido: A–F nativos; G–H legacy Tallas/Colores (no pisar);
 * I+ Kapso.
 */
const PEDIDO_ATTR_HEADERS = {
  I: "Producto base",
  J: "Cuello",
  K: "Largo Manga",
  L: "Género",
  M: "Deportes",
  N: "Otros atributos",
  O: "Comentario",
};

/**
 * Aprobación: A–B nativos; C–F persona; G+ principales + otros + comentario.
 */
const FORMULARIO_HEADERS = {
  C: "Nombre en camiseta",
  D: "Numero en camiseta",
  E: "Talla uniforme",
  F: "Color medias",
  G: "Producto base",
  H: "Cuello",
  I: "Largo Manga",
  J: "Género",
  K: "Deportes",
  L: "Otros atributos",
  M: "Comentario",
};

function cell(content, style = null) {
  const c = { content: content == null ? "" : String(content) };
  if (style != null) c.style = style;
  return c;
}

function findSheet(snapshot, nameRe) {
  const sheets = snapshot?.sheets || [];
  return sheets.find((s) => nameRe.test(String(s?.name || ""))) || null;
}

function findProductosSheet(snapshot) {
  return findSheet(snapshot, PRODUCTOS_SHEET_RE) || snapshot?.sheets?.[1] || null;
}

/** Renombra Pedido → Productos del pedido solo si no hay fórmulas que referencien Pedido!. */
function renamePedidoSheet(snapshot) {
  const raw = JSON.stringify(snapshot || {});
  if (/Pedido!/i.test(raw)) return snapshot;
  const sheet = findSheet(snapshot, /^pedido$/i);
  if (sheet) sheet.name = PRODUCTOS_SHEET_NAME;
  return snapshot;
}

function cellContent(val) {
  if (val == null) return "";
  if (typeof val === "object") return String(val.content ?? "");
  return String(val);
}

function isFormulaCell(val) {
  return cellContent(val).trim().startsWith("=");
}

function setHeaderIfNeeded(sheet, addr, label) {
  sheet.cells = sheet.cells || {};
  const cur = cellContent(sheet.cells[addr]);
  if (!cur || cur === label || !isFormulaCell(sheet.cells[addr])) {
    sheet.cells[addr] = cell(label);
  }
}

function expandTableRange(sheet, range) {
  if (!Array.isArray(sheet.tables) || !sheet.tables.length) return;
  sheet.tables = sheet.tables.map((t) => ({
    ...t,
    range: range || t.range,
  }));
}

function principalFromDecomp(decomp) {
  const p = decomp?.principal || decomp?.attributes || {};
  return {
    cuello: p.cuello || "",
    manga: p.manga || "",
    genero: p.genero || "",
    deporte: p.deporte || "",
  };
}

/** Plantilla venta nativa: formulas Pedido!/XLOOKUP/ODOO.LIST — no expandir tablas ni renombrar. */
function isNativePlantillaFormulario(snapshot) {
  const raw = JSON.stringify(snapshot || {});
  return /Pedido!/i.test(raw) && /XLOOKUP|SEQUENCE|ODOO\.LIST/i.test(raw);
}

/**
 * Escribe I–O en Productos del pedido. No toca A–F ni G–H.
 * En Formulario nativo (Plantilla venta) es no-op: Pedido lo llena ODOO.LIST.
 */
function ensurePedidoAttributeColumns(
  snapshot,
  resolvedLines = [],
  orderLines = null
) {
  if (isNativePlantillaFormulario(snapshot)) return snapshot;
  renamePedidoSheet(snapshot);
  const sheet = findProductosSheet(snapshot);
  if (!sheet) return snapshot;
  sheet.cells = sheet.cells || {};

  for (const [col, label] of Object.entries(PEDIDO_ATTR_HEADERS)) {
    setHeaderIfNeeded(sheet, `${col}1`, label);
  }
  expandTableRange(sheet, "A1:O80");

  const linesForRows = buildPedidoRowPlan(resolvedLines, orderLines);
  linesForRows.forEach((entry, i) => {
    const row = i + 2;
    if (!entry) {
      for (const col of Object.keys(PEDIDO_ATTR_HEADERS)) {
        sheet.cells[`${col}${row}`] = cell("");
      }
      return;
    }
    const decomp = decomposeProductForSpreadsheet(
      entry.display_name || entry.product_text || entry.product_base,
      {
        ...(entry.attributes || {}),
        genero: entry.genero || entry.attributes?.genero,
        deporte: entry.deporte || entry.attributes?.deporte,
      },
      entry.comments || ""
    );
    const p = principalFromDecomp(decomp);
    sheet.cells[`I${row}`] = cell(decomp.product_base);
    sheet.cells[`J${row}`] = cell(p.cuello);
    sheet.cells[`K${row}`] = cell(p.manga);
    sheet.cells[`L${row}`] = cell(p.genero);
    sheet.cells[`M${row}`] = cell(p.deporte);
    sheet.cells[`N${row}`] = cell(decomp.otros_atributos || "");
    sheet.cells[`O${row}`] = cell(decomp.comments || "");
  });

  return snapshot;
}

function buildPedidoRowPlan(resolvedLines = [], orderLines = null) {
  if (Array.isArray(orderLines) && orderLines.length) {
    return orderLines.map((ol) => {
      const name = compact(ol.name || ol.product_id?.[1] || "");
      if (/dise[nñ]o/i.test(name)) {
        return {
          display_name: name,
          product_base: "Diseño",
          attributes: {},
          comments: "",
        };
      }
      const match =
        (resolvedLines || []).find(
          (rl) =>
            Number(rl.product_variant_id || 0) ===
              Number(ol.product_id?.[0] || ol.product_id || 0) ||
            compact(rl.product_text) === name ||
            name.includes(compact(rl.product_base))
        ) || null;
      return {
        display_name: name,
        product_text: match?.product_text || name,
        product_base: match?.product_base,
        attributes: match?.attributes || {},
        genero: match?.genero,
        deporte: match?.deporte || match?.attributes?.deporte,
        comments: match?.comments || "",
      };
    });
  }
  return (resolvedLines || []).filter(
    (l) => !/dise[nñ]o/i.test(l.product_base || l.product_text || "")
  );
}

function fillFormularioPeople(
  snapshot,
  { detail = {}, resolvedLines = [], orderLines = null } = {}
) {
  const sheet =
    findSheet(snapshot, /formulario|aprobaci/i) || snapshot?.sheets?.[0];
  if (!sheet) return { snapshot, filled: 0 };
  sheet.cells = sheet.cells || {};

  const native = isNativePlantillaFormulario(snapshot);
  const people = peopleForSpreadsheet(detail);
  const meta = detail || {};

  if (native) {
    // Solo C–F (Nombre, Número, Talla, Color media). No tocar A–B ni tablas.
    for (const addr of Object.keys(sheet.cells)) {
      const m = addr.match(/^([C-F])(\d+)$/);
      if (m && Number(m[2]) >= 2) delete sheet.cells[addr];
    }
    let filled = 0;
    people.forEach((person, i) => {
      const row = i + 2;
      sheet.cells[`C${row}`] = cell(person.nombre || "");
      sheet.cells[`D${row}`] = cell(person.numero || "");
      sheet.cells[`E${row}`] = cell(person.talla || "");
      sheet.cells[`F${row}`] = cell(person.color_medias || meta.color_media || "");
      filled += 1;
    });
    return { snapshot, filled, mode: "native_aprobacion_cf" };
  }

  for (const [col, label] of Object.entries(FORMULARIO_HEADERS)) {
    setHeaderIfNeeded(sheet, `${col}1`, label);
  }
  if (!cellContent(sheet.cells.A1)) sheet.cells.A1 = cell("Idx");
  if (!cellContent(sheet.cells.B1)) sheet.cells.B1 = cell("Producto");
  expandTableRange(sheet, "A1:M200");

  const productLines = (resolvedLines || []).filter(
    (l) =>
      Number(l.quantity || 0) > 0 &&
      !/dise[nñ]o/i.test(l.product_base || l.product_text || "")
  );
  const defaultLine = productLines[0] || null;
  const defaultDecomp = defaultLine
    ? decomposeProductForSpreadsheet(
        defaultLine.product_text || defaultLine.product_base,
        {
          ...(defaultLine.attributes || {}),
          deporte: defaultLine.attributes?.deporte || meta.disciplina,
          genero: defaultLine.attributes?.genero,
        },
        defaultLine.comments || ""
      )
    : null;

  for (const addr of Object.keys(sheet.cells)) {
    const m = addr.match(/^([C-M])(\d+)$/);
    if (m && Number(m[2]) >= 2) delete sheet.cells[addr];
  }

  let filled = 0;

  function writeAttrRow(row, decomp, person = null) {
    const p = principalFromDecomp(decomp);
    sheet.cells[`G${row}`] = cell(decomp.product_base || "");
    sheet.cells[`H${row}`] = cell(p.cuello);
    sheet.cells[`I${row}`] = cell(p.manga);
    sheet.cells[`J${row}`] = cell(p.genero || person?.genero || "");
    sheet.cells[`K${row}`] = cell(p.deporte || "");
    sheet.cells[`L${row}`] = cell(decomp.otros_atributos || "");
    sheet.cells[`M${row}`] = cell(decomp.comments || "");
  }

  if (people.length) {
    people.forEach((person, i) => {
      const row = i + 2;
      const line =
        productLines.find(
          (l) =>
            l.line_id === person.resolved_line_id ||
            l.product_text === person.product_line_key ||
            l.line_id === person.product_line_key
        ) || defaultLine;
      const generoFromPerson =
        /fem/i.test(person.genero || person.grupo || "")
          ? "femenino"
          : /masc/i.test(person.genero || person.grupo || "")
            ? "masculino"
            : "";
      const decomp = line
        ? decomposeProductForSpreadsheet(
            line.product_text || line.product_base,
            {
              ...(line.attributes || {}),
              genero: line.attributes?.genero || generoFromPerson,
              deporte: line.attributes?.deporte || meta.disciplina,
              manga: line.attributes?.manga || person.manga,
            },
            [line.comments, person.comentarios].filter(Boolean).join(" · ")
          )
        : {
            product_base: "",
            principal: { genero: generoFromPerson },
            attributes: { genero: generoFromPerson },
            otros_atributos: "",
            comments: person.comentarios || "",
          };

      if (!sheet.cells[`A${row}`] || !isFormulaCell(sheet.cells[`A${row}`])) {
        if (!sheet.cells[`A${row}`]) sheet.cells[`A${row}`] = cell(String(i + 1));
      }
      if (!sheet.cells[`B${row}`] || !isFormulaCell(sheet.cells[`B${row}`])) {
        if (!sheet.cells[`B${row}`] && decomp.product_base) {
          sheet.cells[`B${row}`] = cell(decomp.product_base);
        }
      }

      sheet.cells[`C${row}`] = cell(person.nombre || "");
      sheet.cells[`D${row}`] = cell(person.numero || "");
      sheet.cells[`E${row}`] = cell(person.talla || "");
      sheet.cells[`F${row}`] = cell(person.color_medias || meta.color_media || "");
      writeAttrRow(row, decomp, { genero: generoFromPerson });
      filled += 1;
    });
  } else if (defaultDecomp) {
    const qty = productLines.reduce((s, l) => s + Number(l.quantity || 0), 0) || 0;
    for (let i = 0; i < qty; i++) {
      writeAttrRow(i + 2, defaultDecomp);
      filled += 1;
    }
  }

  return { snapshot, filled, mode: "legacy_attrs" };
}

function parsePeopleFromSpreadsheet(snapshot) {
  const sheet =
    findSheet(snapshot, /formulario|aprobaci/i) || snapshot?.sheets?.[0];
  if (!sheet?.cells) return [];
  const byRow = {};
  for (const [addr, val] of Object.entries(sheet.cells)) {
    const m = addr.match(/^([A-M])(\d+)$/);
    if (!m) continue;
    const row = Number(m[2]);
    if (row < 2) continue;
    if (isFormulaCell(val) && (m[1] === "A" || m[1] === "B")) continue;
    byRow[row] = byRow[row] || {};
    byRow[row][m[1]] = compact(val?.content ?? val);
  }
  return Object.keys(byRow)
    .map(Number)
    .sort((a, b) => a - b)
    .map((row) => {
      const r = byRow[row];
      if (!r.C && !r.E && !r.M) return null;
      return {
        person_id: `sheet_${row}`,
        identity: {
          display_name: r.C || "",
          print_name: r.C || "",
          number: r.D || "",
        },
        components: [
          {
            type: "uniforme",
            size: r.E || "",
            comment: [r.M, r.L].filter(Boolean).join(" · "),
            sleeve: r.I || "",
          },
        ],
        comments: r.M || "",
        color_medias: r.F || "",
        product_base: r.G || r.B || "",
        attributes: {
          cuello: r.H || "",
          manga: r.I || "",
          genero: r.J || "",
          deporte: r.K || "",
        },
        otros_atributos: r.L || "",
      };
    })
    .filter(Boolean);
}

function parsePedidoAttributes(snapshot) {
  const sheet = findProductosSheet(snapshot);
  if (!sheet?.cells) return [];
  const byRow = {};
  for (const [addr, val] of Object.entries(sheet.cells)) {
    const m = addr.match(/^([I-O])(\d+)$/);
    if (!m) continue;
    const row = Number(m[2]);
    if (row < 2) continue;
    byRow[row] = byRow[row] || {};
    byRow[row][m[1]] = compact(val?.content ?? val);
  }
  return Object.keys(byRow)
    .map(Number)
    .sort((a, b) => a - b)
    .map((row) => {
      const r = byRow[row];
      if (!r.I && !r.O && !r.N) return null;
      return {
        line_id: `pedido_${row}`,
        product_base: r.I || "",
        attributes: {
          cuello: r.J || "",
          manga: r.K || "",
          genero: r.L || "",
          deporte: r.M || "",
        },
        otros_atributos: r.N || "",
        comments: r.O || "",
      };
    })
    .filter(Boolean);
}

function applyLifeFormularioFill(
  snapshot,
  { detail, resolvedLines, orderLines } = {}
) {
  const clone = JSON.parse(JSON.stringify(snapshot || { sheets: [] }));
  ensurePedidoAttributeColumns(clone, resolvedLines, orderLines);
  const { filled, mode } = fillFormularioPeople(clone, {
    detail,
    resolvedLines,
    orderLines,
  });
  return { snapshot: clone, filled, mode: mode || "legacy_attrs" };
}

function buildMinimalLifeFormularioSnapshot() {
  return {
    version: "18.3.1",
    sheets: [
      {
        id: "formulario",
        name: "Formulario Life (Aprobación nombres, tallas y numero)",
        colNumber: 16,
        rowNumber: 200,
        cells: {
          A1: cell("Idx"),
          B1: cell("Producto"),
        },
        tables: [
          {
            range: "A1:M200",
            type: "static",
            config: {
              hasFilters: true,
              numberOfHeaders: 1,
              bandedRows: true,
              styleId: "TableStyleMedium2",
            },
          },
        ],
      },
      {
        id: "pedido",
        name: "Pedido",
        colNumber: 16,
        rowNumber: 80,
        cells: {
          A1: cell("Producto"),
          B1: cell("Cantidad"),
        },
        tables: [
          {
            range: "A1:O80",
            type: "static",
            config: { numberOfHeaders: 1, bandedRows: true, styleId: "TableStyleMedium5" },
          },
        ],
      },
    ],
    lists: {},
    settings: { locale: { code: "es_ES" } },
  };
}

const PEDIDO_HEADERS = PEDIDO_ATTR_HEADERS;
const ensureFormularioHeaders = (snapshot) => {
  const sheet = findSheet(snapshot, /formulario|aprobaci/i);
  if (!sheet) return snapshot;
  for (const [col, label] of Object.entries(FORMULARIO_HEADERS)) {
    setHeaderIfNeeded(sheet, `${col}1`, label);
  }
  return snapshot;
};


/**
 * sync_order_draft_from_odoo — Kapso ← Odoo (fuente de verdad).
 * Reconstruye resolved_lines + people desde sale.order + spreadsheet.
 */
async function odooRpc(env, service, method, args) {
  const resp = await fetch(`${env.ODOO_URL}/jsonrpc`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      method: "call",
      params: { service, method, args },
    }),
  });
  const json = await resp.json();
  if (json?.error) throw new Error(json.error?.message || "Odoo RPC error");
  return json.result;
}

function decodeSnapshot(b64) {
  if (!b64 || b64 === false) return null;
  try {
    const binary = atob(String(b64));
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    try {
      // Node fallback
      const raw = Buffer.from(b64, "base64").toString("utf8");
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }
}

async function syncOrderDraftFromOdoo(env, { orderId, orderName } = {}) {
  if (!env?.ODOO_URL || !env?.ODOO_DB || !env?.ODOO_USERNAME || !env?.ODOO_PASSWORD) {
    return { ok: false, error: "odoo_unavailable" };
  }
  const uid = await odooRpc(env, "common", "authenticate", [
    env.ODOO_DB,
    env.ODOO_USERNAME,
    env.ODOO_PASSWORD,
    {},
  ]);
  if (!uid) return { ok: false, error: "auth_failed" };

  const executeKw = (model, method, positionalArgs = [], kw = {}) =>
    odooRpc(env, "object", "execute_kw", [
      env.ODOO_DB,
      uid,
      env.ODOO_PASSWORD,
      model,
      method,
      positionalArgs,
      kw,
    ]);

  let soId = Number(orderId || 0) || null;
  if (!soId && orderName) {
    const found = await executeKw(
      "sale.order",
      "search_read",
      [[["name", "ilike", String(orderName).replace(/^S0*/i, "")]]],
      { fields: ["id", "name"], limit: 5 }
    );
    const exact = (found || []).find(
      (o) => String(o.name).toUpperCase() === String(orderName).toUpperCase()
    );
    soId = exact?.id || found?.[0]?.id || null;
  }
  if (!soId) return { ok: false, error: "order_not_found" };

  const orders = await executeKw(
    "sale.order",
    "read",
    [[soId]],
    {
      fields: [
        "id",
        "name",
        "state",
        "note",
        "partner_id",
        "order_line",
        "client_order_ref",
        "spreadsheet_ids",
      ],
    }
  );
  const order = orders?.[0];
  if (!order) return { ok: false, error: "order_not_found" };

  const lines = await executeKw(
    "sale.order.line",
    "search_read",
    [[["order_id", "=", soId], ["display_type", "=", false]]],
    {
      fields: [
        "id",
        "name",
        "product_id",
        "product_uom_qty",
        "price_unit",
        "product_template_id",
      ],
    }
  );

  const resolved_lines = [];
  for (let i = 0; i < (lines || []).length; i++) {
    const line = lines[i];
    const productId = line.product_id?.[0];
    if (!productId) continue;
    if (/dise[nñ]o/i.test(line.name || line.product_id?.[1] || "")) continue;

    let ptavs = [];
    const products = await executeKw(
      "product.product",
      "read",
      [[productId]],
      {
        fields: [
          "id",
          "display_name",
          "product_tmpl_id",
          "product_template_attribute_value_ids",
          "list_price",
        ],
      }
    );
    const product = products?.[0];
    if (product?.product_template_attribute_value_ids?.length) {
      ptavs = await executeKw(
        "product.template.attribute.value",
        "read",
        [product.product_template_attribute_value_ids],
        { fields: ["id", "name", "attribute_id"] }
      );
    }
    const split = splitProductDisplayName(product?.display_name || line.name);
    resolved_lines.push(
      buildResolvedLine(
        {
          line_id: `odoo_line_${line.id}`,
          product_text: product?.display_name || line.name,
          product_base: split.product_base,
          product_tmpl_id: product?.product_tmpl_id?.[0] || line.product_template_id?.[0],
          product_variant_id: productId,
          quantity: line.product_uom_qty,
          unit_cop: line.price_unit,
          confidence: "high",
          attributes: {
            ...split.embedded_attrs,
            ...attributesFromOdooPtavs(ptavs),
          },
        },
        i
      )
    );
  }

  let spreadsheetId = null;
  let spreadsheetUrl = null;
  let people = [];
  let pedidoAttrs = [];
  const sheetIds = order.spreadsheet_ids || [];
  if (sheetIds.length) {
    spreadsheetId = sheetIds[sheetIds.length - 1];
    const sheets = await executeKw(
      "sale.order.spreadsheet",
      "read",
      [[spreadsheetId]],
      { fields: ["id", "name", "spreadsheet_snapshot", "order_id"] }
    );
    const sheet = sheets?.[0];
    const snap = decodeSnapshot(sheet?.spreadsheet_snapshot);
    if (snap) {
      people = parsePeopleFromSpreadsheet(snap);
      pedidoAttrs = parsePedidoAttributes(snap);
      // merge pedido attrs into resolved lines by index
      pedidoAttrs.forEach((pa, idx) => {
        if (resolved_lines[idx]) {
          resolved_lines[idx].attributes = {
            ...resolved_lines[idx].attributes,
            ...pa.attributes,
          };
          if (pa.comments) resolved_lines[idx].comments = pa.comments;
          if (pa.product_base) resolved_lines[idx].product_base = pa.product_base;
        }
      });
    }
    spreadsheetUrl = `${env.ODOO_URL}/odoo/sales/${soId}/sale-order-spreadsheet/${spreadsheetId}`;
  }

  const detail = {
    schema_version: "life_order_people_v1",
    source: "odoo_sync",
    parse_status: "ok",
    people,
    person_count: people.length,
    rows: people.map((p) => ({
      nombre: p.identity?.print_name || "",
      numero: p.identity?.number || "",
      talla: p.components?.[0]?.size || "",
      comentario: p.comments || "",
      resolved_line_id: p.resolved_line_id || "",
    })),
  };

  return {
    ok: true,
    order: {
      id: order.id,
      name: order.name,
      state: order.state,
      partner_id: order.partner_id,
    },
    order_draft: {
      detail,
      commercial: {
        lines: resolved_lines.map((l) => ({
          product_text: l.product_text,
          quantity: l.quantity,
          category: l.category,
        })),
        resolved_lines,
      },
      spreadsheet: {
        id: spreadsheetId,
        url: spreadsheetUrl,
        status: people.length ? "complete" : "partial",
        source_of_truth: "odoo",
      },
      write: {
        status: "ready",
        code: "synced_from_odoo",
        synced_at: new Date().toISOString(),
      },
    },
  };
}



/**
 * Kapso tool: sync-order-draft-from-odoo
 */
function jsonResponse(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

async function handler(request, env) {
  const body = await request.json().catch(() => ({}));
  const input = body?.input || {};
  const vars = body?.execution_context?.vars || {};
  const now = new Date().toISOString();

  if (vars?.user?.role !== "staff") {
    return jsonResponse({ ok: false, error: "staff_only" }, 403);
  }

  const orderId =
    Number(input.order_id || vars?.order?.id || vars?.order_correction?.target_order_id || 0) ||
    null;
  const orderName =
    input.order_name || vars?.order?.name || vars?.order_correction?.target_order_name || null;

  try {
    const result = await syncOrderDraftFromOdoo(env, { orderId, orderName });
    if (!result.ok) {
      return jsonResponse({
        ok: false,
        error: result.error,
        vars: {
          service: {
            last_call_name: "sync_order_draft_from_odoo",
            last_call_status: "error",
            last_call_at: now,
            fallback_message: `No pude sincronizar desde Odoo (${result.error}).`,
          },
        },
      });
    }
    return jsonResponse({
      ok: true,
      message: `Borrador actualizado desde Odoo ${result.order.name} (fuente de verdad).`,
      vars: {
        order: {
          id: result.order.id,
          name: result.order.name,
          status: result.order.state,
        },
        order_draft: result.order_draft,
        fidelity: mergeFidelityAfterSync(vars.fidelity, result.order_draft, now),
        service: {
          last_call_name: "sync_order_draft_from_odoo",
          last_call_status: "ready",
          last_call_at: now,
          fallback_message: null,
        },
      },
    });
  } catch (error) {
    return jsonResponse({
      ok: false,
      error: String(error?.message || error),
      vars: {
        service: {
          last_call_name: "sync_order_draft_from_odoo",
          last_call_status: "error",
          last_call_at: now,
          fallback_message: "Fallo al leer el pedido en Odoo.",
        },
      },
    });
  }
}


function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

function normalizeLine(line = {}) {
  return {
    product_variant_id: num(line.product_variant_id || line.odoo_product_id || line.product_id),
    product_text: compact(line.product_text || line.product_base || line.name).toLowerCase(),
    quantity: num(line.quantity),
    attributes: {
      cuello: compact(line.attributes?.cuello || line.collar).toLowerCase(),
      manga: compact(line.attributes?.manga || line.sleeves).toLowerCase(),
      tela: compact(line.attributes?.tela || line.material).toLowerCase(),
    },
  };
}

function lineKey(line) {
  if (line.product_variant_id) return `id:${line.product_variant_id}`;
  return `t:${line.product_text}|${line.attributes.cuello}|${line.attributes.manga}|${line.attributes.tela}`;
}

function mergeFidelityAfterSync(prevFidelity, orderDraft, now) {
  const fidelity = { ...(prevFidelity || {}) };
  const snapshot = fidelity.kapso_snapshot;
  if (!snapshot) return fidelity;

  const kapsoLines = (snapshot.resolved_lines || []).map(normalizeLine).filter((l) => l.quantity > 0);
  const current =
    orderDraft?.commercial?.resolved_lines || orderDraft?.commercial?.lines || [];
  const currentLines = (Array.isArray(current) ? current : [])
    .map(normalizeLine)
    .filter((l) => l.quantity > 0);

  if (!kapsoLines.length) {
    return {
      ...fidelity,
      pass_clean: false,
      retention_pct: null,
      last_compared_at: now,
      last_compare_source: "sync_order_draft_from_odoo",
    };
  }

  const byKey = new Map(currentLines.map((l) => [lineKey(l), l]));
  let matched = 0;
  let total = 0;
  let linesChanged = 0;
  for (const k of kapsoLines) {
    const c = byKey.get(lineKey(k));
    total += 3;
    if (!c) {
      linesChanged += 1;
      continue;
    }
    if (k.quantity === c.quantity) matched += 1;
    else linesChanged += 1;
    if (!k.product_variant_id || k.product_variant_id === c.product_variant_id) matched += 1;
    else linesChanged += 1;
    if (!k.product_text || k.product_text === c.product_text) matched += 1;
    else linesChanged += 1;
  }
  for (const c of currentLines) {
    if (!kapsoLines.some((k) => lineKey(k) === lineKey(c))) linesChanged += 1;
  }
  const retention_pct = total > 0 ? Math.round((1000 * matched) / total) / 10 : 0;
  return {
    ...fidelity,
    pass_clean: linesChanged === 0 && retention_pct >= 99.9,
    retention_pct,
    correction_burden: Math.round(10 * (100 - retention_pct)) / 10,
    lines_changed: linesChanged,
    last_compared_at: now,
    last_compare_source: "sync_order_draft_from_odoo",
  };
}

